TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_OPERACOES do;
TRACE >>> TEMP_Palas_Operacoes_Tratadas_2022_2023;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF
//DIM_OPERACOES DO Palas_Operacoes_Tratadas_2022_2023 COM LINK TABLE
// --------------------------------------------------------------------------------------

// DIM_OPERACOES DO Palas_Operacoes_Tratadas_2022_2023:
CONCATENATE(DIM_OPERACOES)
LOAD Distinct
    AutoNumberHash128(ID_OPERACAO) AS [%ID_OPERACAO_KEY],
    ID_OPERACAO,
    IPL AS Caso_de_Operação,
    APPLYMAP('REGIAOMapping', "UF") AS "Região",
// ACRESCENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
	COALESCE(Date(DT_HOMOLOGACAO), Date(DT_DEFLAGRACAO)) as "Data da Homologação",
    COALESCE(YEAR(date(DT_HOMOLOGACAO)), YEAR(date(DT_DEFLAGRACAO))) as "Ano da Homologação",
    COALESCE(MONTH(date(DT_HOMOLOGACAO)), MONTH(date(DT_DEFLAGRACAO))) as "Mês da Homologação",
    COALESCE(Num(MONTH(date(DT_HOMOLOGACAO)), Num(MONTH(date(DT_DEFLAGRACAO))))) as "Mês (Num) da Homologação",
//
    Date(DT_DEFLAGRACAO) as "Data da Deflagração",
    YEAR(date(DT_DEFLAGRACAO)) as "Ano da Deflagração",
    MONTH(date(DT_DEFLAGRACAO)) as "Mês da Deflagração",
    Num(MONTH(date(DT_DEFLAGRACAO))) as "Mês (Num) da Deflagração",
//
    NOME_OPERACAO,
    UNIDADE AS UNIDADE_OPERACAO,
    UF AS UF_OPERACAO,
   'Homologada' AS ETAPAOPERACAO,
    IF(
        NOT IsNull(UNIDADE) AND (
            Match(Right(UNIDADE, 8),
                $(vUnidadeFronteiraSr)
            ) > 0
            OR
            Match(Right(UNIDADE, 10),
                $(vUnidadeFronteiraDpf)
            ) > 0
        ),
        'SIM',
        'NÃO'
    ) AS "UNIDADE_FRONTEIRA",

//  Unidade, Área de Atribuição, Diretoria e CG da Operação
// 	UNIDADE AS [%UNIDADE_OPERACAO], // Texto
	UF AS "Unidade UF da Operação", // Texto
    UNIDADE AS "Unidade Sigla da Operação", // Texto
//
    // Área de atribuição da operação
    APPLYMAP('PALASAREAATRIBUICAOMapping', AREAATRIBUICAOPALAS)
    AS "Área de Atribuição da Operação",
    // Diretoria da operação
    APPLYMAP('PALASAREADIRETORIAMapping', AREAATRIBUICAOPALAS)
    AS "Diretoria da Operação",
    // Coordenação-Geral da operação
    APPLYMAP('PALASAREACOORDENACAOGERALMapping', AREAATRIBUICAOPALAS)
    AS "Coordenação-Geral da Operação"

RESIDENT TEMP_Palas_Operacoes_Tratadas_2022_2023;

// DROP TABLE TEMP_Palas_Operacoes_Tratadas_2022_2023;

// DROP TABLE TEMP_SIGACrimHomologadas;

CALL StoreAndDrop('DIM_OPERACOES', '$(vCaminhoTransformadosV3)');
