TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

DIM_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO:
Load Distinct
    AutoNumberHash128(id_evento_apreensao) AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY],
    id_evento_apreensao,
    cd_item_epol_fk,
    cd_categoria_epol_fk,
    cd_classe_epol_fk,
    nr_apreensao,
    Date(dt_apreensao) as "Data do Evento Apreensão Externo/Estrangeiro", // Data como texto
    year(dt_apreensao) as "Ano do Evento Apreensão Externo/Estrangeiro", // Data como texto
    month(dt_apreensao) as "Mês do Evento Apreensão Externo/Estrangeiro", // Data como texto
    Num(MONTH(dt_apreensao)) as  "Mês (Num) do Evento Apreensão Externo/Estrangeiro", // Data como texto
    ds_apreensao,
    nr_caso,
    ds_item,
//     qt_item,
//     st_selecionado,
    ds_local_apreensao,
    un_item
RESIDENT TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;

CALL StoreAndDrop('DIM_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO', '$(vCaminhoTransformadosV3)');