TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_UNIDADE do TEMP_DIM_UNIDADE;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
DIM_UNIDADE:


Hierarchy("Unidade ID", "Unidade Responsável ID", "Unidade Sigla", "Unidade Sigla Superior", "Unidade Sigla","Caminho Unidade Sigla","->","Nível") 


LOAD Distinct
    AutoNumberHash128("Unidade Sigla") AS [%UNIDADE_KEY],
//     "Unidade ID" AS [%UNIDADE_ID],
    "Unidade ID",
    ApplyMap('MapCorrigeUnidSuperiorDpfCacDpfGra', "Unidade ID","Unidade Responsável ID")
    AS "Unidade Responsável ID",
    "Unidade Sigla",
    "Descrição Unidade Sigla",
    // "Unidade Situação",
    "Unidade UF",
    "Unidade Região",
    // "Unidade CNPJ",
    // "Unidade SiapeCad",
    // "Unidade Responsável Sigla",
    // "Unidade Responsável UF",
    "Unidade Email",
    "Unidade Organizacional",
    "Unidade Tipo",
    "Unidade SIORG",
    "Unidade Conduz IPL",
    "Unidade Adicional Fronteira",
    "Unidade Circunscrição",
    "Unidade Dotação",
    // "Unidade Gestora Sigla",
    // "Unidade Gestora UF",
    // "Unidade Patrimonial Sigla",
    // "Unidade Patrimonial UF",

    "Unidade Município Nome",
    "Unidade Município IBGE",
    "Unidade Estado UF",
    "Unidade Estado Nome",
    "Unidade PF Área",
    "Unidade Circunscrição Município Sede",
    "Unidade Circunscrição UF Sede",
    "Unidade Lotação Sigla",
    "Unidade Endereço",
    "Unidade Endereço CEP",
    "Unidade Endereço UF"
    // "Unidade Latitude",
    // "Unidade Longitude"
RESIDENT TEMP_DIM_UNIDADE
WHERE "Unidade Situação" = 'Ativa';

CALL StoreCsv('DIM_UNIDADE', '$(vCaminhoTabelasTeste)' & 'COM_HIERARQUIA_');

// CALL StoreAndDrop('DIM_UNIDADE', '$(vCaminhoTransformadosV3)');
