TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_HIERARQUIA_TECNICA do;
TRACE >>> TEMP_DIM_HIERARQUIA_TECNICA;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
DIM_HIERARQUIA_TECNICA:
LOAD Distinct
    AutoNumberHash128("Unidade Sigla") AS [%UNIDADE_KEY],
//     "Unidade ID" AS [%UNIDADE_ID],
    IF(
        LEN(TRIM("Unidades Centrais"))>0,
        'Sim',
        'Não'
    ) AS "É Unidade Central",
    IF(
        LEN(TRIM("Unidades Regionais"))>0,
        'Sim',
        'Não'
    ) AS "É Unidade Regional",
    IF(
        LEN(TRIM("Bases"))>0,
        'Sim',
        'Não'
    ) AS "É Unidade Base",
    IF(
        LEN(TRIM("Unidades Descentralizadas"))>0,
        'Sim',
        'Não'
    ) AS "É Unidade Descentralizada",
    "Unidade Sigla Raiz",
    "Unidade Sigla Unificada",
    "Unidade Central",
    "Unidade Central Investigativa",
    "Unidade Central Não Investigativa",
    "Unidade Regional",
    "Unidade Regional Investigativa",
    "Unidade Regional Não Investigativa",
    "Unidade Base",
    "Unidade Descentralizada",
    "Unidade Descentralizada Investigativa",
    "Unidade Descentralizada Não Investigativa",
    "Hierarquia Administrativa",
    "Hierarquia Técnica",
    COALESCE("PJ/NPJ",'DESCONHECIDO') AS [PJ/NPJ],
    IF(
        NOT ISNULL("Unidade Central"),
        'Unidade Central',
        IF(
             NOT ISNULL("Unidade Regional"),
            'Unidade Regional',
            IF(
                 NOT ISNULL("Base"),
                'Base',
                IF(
                     NOT ISNULL("Unidade Descentralizada"),
                    'Unidade Descentralizada',
                    ''
                )
            )
        )
    )
    AS "Unidade Abrangência",
    IF(
        NOT ISNULL("Unidade Central Investigativa"),
        'Unidade Central Investigativa',
        IF(
            NOT ISNULL("Unidade Central Não Investigativa"),
            'Unidade Central Não Investigativa',
            IF(
                NOT ISNULL("Unidade Regional Investigativa"),
                'Unidade Regional Investigativa',
                IF(
                    NOT ISNULL("Unidade Regional Não Investigativa"),
                    'Unidade Regional Não Investigativa',
                    IF(
                        NOT ISNULL("Base"),
                        'Base',
                        IF(
                            NOT ISNULL("Unidade Descentralizada Investigativa"),
                            'Unidade Descentralizada Investigativa',
                            IF(
                                NOT ISNULL("Unidade Descentralizada Não Investigativa"),
                                'Unidade Descentralizada Não Investigativa',
                                ''
                            )
                        )
                    )
                )
            )
        )
    )
    AS "Unidade PJ/NPJ"
RESIDENT TEMP_DIM_HIERARQUIA_TECNICA
WHERE LEN(TRIM("Unidade Sigla"))>0;

CALL StoreAndDrop('DIM_HIERARQUIA_TECNICA', '$(vCaminhoTransformadosV3)');

DROP TABLE TEMP_DIM_SERVIDOR_ATIVO;

DROP TABLE TEMP_DIM_UNIDADE;

DROP TABLE TEMP_DIM_HIERARQUIA_TECNICA;