TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_HIERARQUIA_UNIDADE_SIGLA_DO_CASO da TEMP_DIM_CASO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
//-----------------------------------------------------------------------------------------------
// Dimensões para filtrar unidades Superintendências, Especializadas, Bases e Descentralizadas
// por Unidade Sigla do Caso
//-----------------------------------------------------------------------------------------------

DIM_HIERARQUIA_UNIDADE_SIGLA_DO_CASO:
LOAD DISTINCT
    AutoNumberHash128("Unidade Sigla do Caso") AS [%UNIDADE_KEY],
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) > 0,
        'Base',
        PICK(
            1 + WildMatch(
                "Unidade Sigla do Caso",
                'PF',
                '*/PF',
                'SR/PF/*',
                '*/SR/PF/*',
                'DPF/*'
                '*/DPF/*'
            ),
            '',
            'Órgão Central',
            'Órgão Central',
            'Órgão Regional',
            'Órgão Regional',
            'Delegacia Descentralizada',
            'Delegacia Descentralizada'
        )
    ) AS "Tipo da Unidade do Caso",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'PF',
                '*/PF'
            ) > 0,
            'Sim',
            'Não'
        )
    ) AS "É Órgão Central",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'PF',
                '*/PF'
            ) > 0,
            "Unidade Sigla do Caso",
            ''
        )
    ) AS "Órgão Central",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'SR/PF/*',
                '*/SR/PF/*'
            ) > 0,
            'Sim',
            'Não'
        )
    ) AS "É Órgão Regional",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'SR/PF/*',
                '*/SR/PF/*'
            ) > 0,
            "Unidade Sigla do Caso",
            ''
        )
    ) AS "Órgão Regional",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                '*/DPF/*',
                'DPF/*'
            ) > 0,
            'Sim',
            'Não'
        )
    ) AS "É Órgão Delegacia Descentralizada",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                '*/DPF/*',
                'DPF/*'
            ) > 0,
            "Unidade Sigla do Caso",
            ''
        )
    ) AS "Órgão Delegacia Descentralizada",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) > 0,
        'Sim',
        'Não'
    ) AS "É Órgão Base",
    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) > 0,
        "Unidade Sigla do Caso",
        ''
    ) AS "Órgão Base",
   PICK(
    	1 + WildMatch(
        "Unidade Sigla do Caso",
        'BABC/*',
        '*/BABC/*',
        'BAC/*',
        '*/BAC/*',
        'BASEPLATANOS/*',
        '*/BASEPLATANOS/*',
        'BEMIG/*',
        '*/BEMIG/*',
        'BRBA/*',
        '*/BRBA/*',
        'FICCO/*',
        '*/FICCO/*',
        'GIASE/*',
        '*/GIASE/*',
        'GISE/*',
        '*/GISE/*',
        'GISECONT/*',
        '*/GISECONT/*',
        'BASEQUADRANTE/*',
        '*/BASEQUADRANTE/*',
        'BASELACOR/*',
        '*/BASELACOR/*'
        )
        ,'Outras',
        'BABC',
        'BABC',
        'BAC',
        'BAC',
        'BASEPLATANOS',
        'BASEPLATANOS',
        'BEMIG',
        'BEMIG',
        'BRBA',
        'BRBA',
        'FICCO',
        'FICCO',
        'GIASE',
        'GIASE',
        'GISE',
        'GISE',
        'GISECONT',
        'GISECONT',
        'BASEQUADRANTE',
        'BASEQUADRANTE',
        'BASELACOR',
        'BASELACOR'
    )
    AS "Base",
    IF(
        WildMatch(
                "Unidade Sigla do Caso",
                'DELECIBER/*',
                '*/DELECIBER/*',
                'DELECOR/*',
                '*/DELECOR/*',
                'DELEFAZ/*',
                '*/DELEFAZ/*',
                'DELEINQUE/*',
                '*/DELEINQUE/*',
                'DELEPAT/*',
                '*/DELEPAT/*',
                'DELEPREV/*',
                '*/DELEPREV/*',
                'DELINST/*',
                '*/DELINST/*',
                'DMA/*',
                '*/DMA/*',
                'DRE/*',
                '*/DRE/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    ) AS "É Delegacia Especializada PJ",
    IF(
        WildMatch(
                "Unidade Sigla do Caso",
                'DELECIBER/*',
                '*/DELECIBER/*',
                'DELECOR/*',
                '*/DELECOR/*',
                'DELEFAZ/*',
                '*/DELEFAZ/*',
                'DELEINQUE/*',
                '*/DELEINQUE/*',
                'DELEPAT/*',
                '*/DELEPAT/*',
                'DELEPREV/*',
                '*/DELEPREV/*',
                'DELINST/*',
                '*/DELINST/*',
                'DMA/*',
                '*/DMA/*',
                'DRE/*',
                '*/DRE/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            "Unidade Sigla do Caso",
            ''
        )
    ) AS "Órgão Especializada PJ",

    IF(
        WildMatch(
            "Unidade Sigla do Caso",
            'BABC/*',
            'BAC/*',
            'BASEPLATANOS/*',
            'BEMIG/*',
            'BRBA/*',
            'FICCO/*',
            'GIASE/*',
            'GISE/*',
            'GISECONT/*',
            'BASEQUADRANTE/*',
            'BASELACOR/*',
            '*/BABC/*',
            '*/BAC/*',
            '*/BASEPLATANOS/*',
            '*/BEMIG/*',
            '*/BRBA/*',
            '*/FICCO/*',
            '*/GIASE/*',
            '*/GISE/*',
            '*/GISECONT/*',
            '*/BASEQUADRANTE/*',
            '*/BASELACOR/*'
        ) = 0,
        PICK(
            1 + WildMatch(
                    "Unidade Sigla do Caso",
                    'DELECIBER/*',
                    '*/DELECIBER/*',
                    'DELECOR/*',
                    '*/DELECOR/*',
                    'DELEFAZ/*',
                    '*/DELEFAZ/*',
                    'DELEINQUE/*',
                    '*/DELEINQUE/*',
                    'DELEPAT/*',
                    '*/DELEPAT/*',
                    'DELEPREV/*',
                    '*/DELEPREV/*',
                    'DELINST/*',
                    '*/DELINST/*',
                    'DMA/*',
                    '*/DMA/*',
                    'DRE/*',
                    '*/DRE/*'
            ),
            '',
            'DELECIBER',
            'DELECIBER',
            'DELECOR',
            'DELECOR',
            'DELEFAZ',
            'DELEFAZ',
            'DELEINQUE',
            'DELEINQUE',
            'DELEPAT',
            'DELEPAT',
            'DELEPREV',
            'DELEPREV',
            'DELINST',
            'DELINST',
            'DMA',
            'DMA',
            'DRE',
            'DRE'
        )
    ) AS "Delegacia Especializada PJ",


    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELECIBER/*',
                '*/DELECIBER/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELECIBER",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELECOR/*',
                '*/DELECOR/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELECOR",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELEFAZ/*',
                '*/DELEFAZ/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELEFAZ",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELEPAT/*',
                '*/DELEPAT/*'
        ) > 0,
		IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELEPAT",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELEPREV/*',
                '*/DELEPREV/*'
        ) > 0,
		IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELEPREV",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DRE/*',
                '*/DRE/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DRE",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELINST/*',
                '*/DELINST/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELINST",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DMA/*',
                '*/DMA/*'
        ) > 0,
        IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DMA",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
                'DELEINQUE/*',
                '*/DELEINQUE/*'
        ) > 0,
		IF(
            WildMatch(
                "Unidade Sigla do Caso",
                'BABC/*',
                'BAC/*',
                'BASEPLATANOS/*',
                'BEMIG/*',
                'BRBA/*',
                'FICCO/*',
                'GIASE/*',
                'GISE/*',
                'GISECONT/*',
                'BASEQUADRANTE/*',
                'BASELACOR/*',
                '*/BABC/*',
                '*/BAC/*',
                '*/BASEPLATANOS/*',
                '*/BEMIG/*',
                '*/BRBA/*',
                '*/FICCO/*',
                '*/GIASE/*',
                '*/GISE/*',
                '*/GISECONT/*',
                '*/BASEQUADRANTE/*',
                '*/BASELACOR/*'
			) = 0,
            'Sim',
            'Não'
        )
    )
	AS "É DELEINQUE",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
            'FICCO/*',
            '*/FICCO/*'
        ) > 0,
		'Sim',
        'Não')
	AS "É FICCO",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
            'GISE/*',
            '*/GISE/*'
        ) > 0,
		'Sim',
        'Não')
	AS "É GISE",
    IF(
    	WildMatch(
            "Unidade Sigla do Caso",
            'BEMIG/*',
            '*/BEMIG/*'
        ) > 0,
		'Sim',
        'Não')
	AS "É BEMIG",
    PICK(
    	1 + WildMatch(
        "Unidade Sigla do Caso",
        '*FICCO/*',
        '*GISE/*',
        '*BEMIG/*',
        '*DELECIBER/*',
        '*DELECOR/*',
        '*DELEFAZ/*',
        '*DELEINQUE/*',
        '*DELEPAT/*',
        '*DELEPREV/*',
        '*DELINST/*',
        '*DMA/*',
        '*DRE/*'
        )
        ,'Outras',
        'FICCO',
        'GISE',
        'BEMIG',
        'DELECIBER',
        'DELECOR',
        'DELEFAZ',
        'DELEINQUE',
        'DELEPAT',
        'DELEPREV',
        'DELINST',
        'DMA',
        'DRE'
    )
    AS "Especializadas e Bases"
RESIDENT LINK_TABLE_APREENSOES_OPERACOES_CASOS
WHERE LEN(TRIM("Unidade Sigla do Caso"))>0;

CALL StoreAndDrop('DIM_HIERARQUIA_UNIDADE_SIGLA_DO_CASO', '$(vCaminhoTransformadosV3)');