DIM_TNBIA:
LOAD distinct
	AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%ITEM_SUBCLASSE_KEY],
	"GestãoBens Item Material Subclasse Código",
    "GestãoBens Item Material ID",
    "GestãoBens Item Material",
    "GestãoBens Item Material Classe",
    "GestãoBens Item Material Categoria"
RESIDENT TEMP_TNBIA
;

CALL StoreAndDrop('DIM_TNBIA', '$(vCaminhoTransformadosV3)');

DROP TABLE TEMP_TNBIA;
