TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_DIM_SERVIDOR_ATIVO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TEMP_DIM_SERVIDOR_ATIVO:
Load 
*
FROM [$(vCaminhoExtraidosV2)TEMP_DIM_SERVIDOR_ATIVO.qvd]
(qvd);

// DROP TABLE TEMP_TEMP_DIM_CASOS;


TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga TEMP_DIM_SERVIDOR_ATIVO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;