TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_Palas_Operacoes_Tratadas_2022_2023;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TEMP_Palas_Operacoes_Tratadas_2022_2023:
Load 
*
FROM [$(vCaminhoExtraidosV2)TEMP_Palas_Operacoes_Tratadas_2022_2023.qvd]
(qvd);

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga TEMP_Palas_Operacoes_Tratadas_2022_2023;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;