TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_TB_MUNICIPIOS_BRASIL;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF
// TEMP_TB_MUNICIPIOS_BRASIL DO TB_MUNICIPIOS_BRASIL COM LINK TABLE
// --------------------------------------------------------------------------------------
// Carregamento da tabela TEMP_TB_MUNICIPIOS_BRASIL a partir do arquivo TB_MUNICIPIOS_BRASIL.qvd

TEMP_TB_MUNICIPIOS_BRASIL:
LOAD
    "Código IBGE",
    // População,
    // Região,
    PontoCidade,
    Latitude_Cidade,
    Longitude_Cidade,
    AreaCidade,
    UF,
    Cidade
    // Mesorregião,
    // Microrregião,
    // CODIGO_IBGE
// FROM [lib://CORP_DADOS_AUXILIARES/qvd/TB_MUNICIPIOS_BRASIL.QVD]
FROM [$(vCarregaTB_MUNICIPIOS_BRASIL)]
(qvd);
