TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF
// TEMP_Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024 DO Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024.xls COM LINK TABLE
// --------------------------------------------------------------------------------------
// Carregamento da tabela TEMP_Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024 a partir do arquivo Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024.xls

TEMP_Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024:
LOAD
    // CD_MUN,
    NM_MUN,
    // CD_RGI,
    // NM_RGI,
    // CD_RGINT,
    // NM_RGINT,
    // CD_UF,
    // NM_UF,
    SIGLA_UF,
    // CD_REGIAO,
    // NM_REGIAO,
    // SIGLA_RG,
    // AREA_TOT,
    TOCA_LIM,
    // "AREA INT",
    // PORC_INT,
    FAIXA_SEDE,
    CID_GEMEA
// FROM [lib://CORP_DICOR_NGE/BI_NGE_ESTATISTICAS/Mun_Faixa_de_Fronteira_Cidades_Gemeas_2024.xls]
// (biff, embedded labels, table is [Faixa de Fronteira - Município 2024$]);
FROM [$(vCarregaMun_Faixa_de_Fronteira_Cidades_Gemeas_2024)]
$(vFormatoMun_Faixa_de_Fronteira_Cidades_Gemeas_2024)
;