TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando Section Access;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
Section Access;
 
LOAD
    "ACCESS",
    "USERID"
FROM [lib://CORP_DICOR_NGE/BI_NGE_ESTATISTICAS/SECTION_ACCESS_TRA_Estatísticas_Criminais_SIGACrim.xlsx]
(ooxml, embedded labels, table is Planilha1); 

Section Application;

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga Section Access;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
