TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Iniciando carga das Métricas de Controle;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

//-----------------------------------------------------------------------------------------------
// Variáveis de métricas
//-----------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------
// Observações: 
//      SomaAnteriores já é o Pareto
//      DtMesAno quando o cálculo inclui o "Tipo do Fato"
//      DtMesAnoDefl quando o cálculo não inclui o "Tipo do Fato"
//-----------------------------------------------------------------------------------------------

/*******************************************************************************
    OBS: 
    - as variáveis de medida mestra que terminam sem 'Tot' deve ser usadas
    nos gráficos que usam dimensões de Unidade ou localizações etc.
    - as variáveis de medida mestra que terminam com 'Tot' deve ser usadas
    nos gráficos que usam dimensões de Data Mês Ano etc. DATA=*TOT
*******************************************************************************/

//-----------------------------------------------------------------------------------------------
// Variáveis de controle
//-----------------------------------------------------------------------------------------------

//Variável de definição dos valores a serem apresentados no formato absoluto ou relativo ao
//efetivo
Set vMostrarValAbsouRelaoEfetouPfEmNum = '0';

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjDtHomPfEmNumeros = 
    [Data da Homologação] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 6), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjDtHomPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjOpDtMesAnoPfEmNumeros = 
    [Data] = {"<@(=MonthStart(Today()))"},
    [Data da Homologação] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 6), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjOpDtMesAnoPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjOpDtMesAnoDeflPfEmNumeros = 
    [Data da Deflagração] = {"<@(=MonthStart(Today()))"},
    [Data da Homologação] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 6), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjOpDtMesAnoDeflPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjOpDtMesAnoCadPfEmNumeros = 
    [Data do Cadastro] = {"<@(=MonthStart(Today()))"},
    [Data da Homologação] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 6), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjOpDtMesAnoCadPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjApreDtMesAnoPfEmNumeros = 
    [Data] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjApreDtMesAnoPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjApreDtMesAnoAprePfEmNumeros = 
    [Data da Apreensão] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjApreDtMesAnoAprePfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjProcDataDtMesAnoPfEmNumeros = 
    [Data] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjProcDataDtMesAnoPfEmNumeros);

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjProcDataDtMesAnoProcDataPfEmNumeros = 
    [Proc_Data Data] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjProcDataDtMesAnoProcDataPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjInstDtMesAnoPfEmNumeros = 
    [Data] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjInstDtMesAnoPfEmNumeros);

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjInstDtMesAnoInstPfEmNumeros = 
    [Data da Instauração] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjInstDtMesAnoInstPfEmNumeros); 

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjRelatDtMesAnoPfEmNumeros = 
    [Data] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjRelatDtMesAnoPfEmNumeros);

// Filtro para mostrar somente operações homologadas até o dia 5 do mês para ser inserida nas
// funções de criação de variáveis one o '@' será substituído por '$' no conteudo da variável
// para permitir a chamada recursiva de variável sem calculo forçado:
SET vConjRelatDtMesAnoRelatPfEmNumeros = 
    [Data do Relatório] = {"<@(=Date(MakeDate(Year(Today()), Num(Month(Today())), 1), 'DD/MM/YYYY'))"}
;

// Caso seja expandido diretamente, fora das subrotinas de criação de variáveis, é necessário
// chamar a subrotina TratarExpansaoMacro logo abaixo da definição da variável
// Call TratarExpansaoMacro(vConjRelatDtMesAnoRelatPfEmNumeros); 

//-----------------------------------------------------------------------------------------------
// Variáveis para registrar os campos selecionados quando a aplicação estiver rodando
//-----------------------------------------------------------------------------------------------

SET vAnoSelecionado = GetFieldSelections([Ano]);

SET vContaDtMesAnoSelecionado = 
	  GetSelectedCount([Ano])
    + GetSelectedCount([Mês])
    + GetSelectedCount([Data]) > 0;

SET vAnoDeflagracaoSelecionado = GetFieldSelections([Ano da Deflagração]);

SET vContaDtMesAnoDeflSelecionado = 
        GetSelectedCount([Ano da Deflagração])
        + GetSelectedCount([Mês da Deflagração])
        + GetSelectedCount([Data da Deflagração]) > 0;

SET vAnoApreensaoSelecionado = GetFieldSelections([Ano da Apreensão]);

SET vContaDtMesAnoApreSelecionado = 
        GetSelectedCount([Ano da Apreensão])
        + GetSelectedCount([Mês da Apreensão])
        + GetSelectedCount([Data da Apreensão]) > 0;

SET vProcDataDataAnoSelecionado = GetFieldSelections([Proc_Data Data Ano]);

SET vContaProcDtDtMesAnoSelecionado = 
        GetSelectedCount([Proc_Data Data Ano])
        + GetSelectedCount([Proc_Data Data Mês])
        + GetSelectedCount([Proc_Data Data]) > 0;

SET vAnoCadastroSelecionado = GetFieldSelections([Ano do Cadastro]);

SET vContaDtMesAnoCadSelecionado = 
        GetSelectedCount([Ano do Cadastro])
        + GetSelectedCount([Mês do Cadastro])
        + GetSelectedCount([Data do Cadastro]) > 0;

SET vAnoInstSelecionado = GetFieldSelections([Ano da Instauração]);

SET vContaDtMesAnoInstSelecionado = 
        GetSelectedCount([Ano da Instauração])
        + GetSelectedCount([Mês da Instauração])
        + GetSelectedCount([Data da Instauração]) > 0;

SET vAnoRelatSelecionado = GetFieldSelections([Ano do Relatório]);

SET vContaDtMesAnoRelatSelecionado = 
        GetSelectedCount([Ano do Relatório])
        + GetSelectedCount([Mês do Relatório])
        + GetSelectedCount([Data do Relatório]) > 0;

SET vAnoEventoSelecionado = GetFieldSelections([Ano do Evento]);

SET vContaDtMesAnoEventoSelecionado = 
        GetSelectedCount([Ano do Evento])
        + GetSelectedCount([Mês do Evento])
        + GetSelectedCount([Data do Evento]) > 0;
