TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando FATO_APREENSOES do TEMP_SIGACrimHomologadas;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF
// FATO_APREENSOES DO SIGACrimHomologadas 2024 COM LINK TABLE
//---------------------------------------------------------------------------------------
// Carregamento da tabela FATO APREENSAO a partir do arquivo SIGACrimHomologadas.qvd
// - das operações (ID_OPERACAO), consideradas como os fatos dos valores registrados como
//   sequestrados no SIGACrim, como "GestãoBens Item ID", para concatenação com a tabela
//   das Apreensoes do ePol carregada anteriormente como a tabela fato APREENSOES
// - cujo Ano da Deflagração é 2024 (where YEAR(DT_DEFLAGRACAO) = 2024) e que foram
//   homologadas até 31/03/2025 (DT_HOMOLOGACAO < '01/04/2025')
// - para fins de concatenação com a table fato APRENSSOES, considerei:
//   - a unidade de deflagração como unidade de apreessão
//      UNIDADE as "GestãoBens Apreensão Unidade Sigla",
//   - a UF de deflagração como unidade de apreensão
//      UF as "GestãoBens Apreensão Unidade UF",
//   - a data de deflagração como data de apreensão
//      DT_DEFLAGRACAO as "Data da Apreensão",
//   - o ano de deflagração como ano de apreensão
//      YEAR(DT_DEFLAGRACAO) as "Ano da Apreensão",
//   - o mês de deflagração como mês de apreensão
//      MONTH(DT_DEFLAGRACAO) as  "Mês da Apreensão",
//   - os campos dos valores dos sequestros realizados nas operações como soma dos 
//     itens apreendidos, no dia da deflagração, vinculando-os a um "GestãoBens Item ID",
//     para poder que somar os valores sequestrados com os valores apreendidos constantes
//     nas Apreensões do ePol, carregadas anteriormente, e não haverá vinculação com um
//     Item Material Subclasse ([GestãoBens Item Material Subclasse Código]), por serem
//     a soma dos bens de várias classes de descapitaliação:
//     VL_TOTAL_SEQUESTRO,
//     VL_SEQUESTRO_VALOR_MOVEIS,
//     VL_SEQUESTRO_VALOR_BLOQUEADO_FINANCEIRO,
//     VL_SEQUESTRO_VALOR_ESTIMADO_IMOVEIS,
//     VL_SEQUESTRO_VALOR_CRIPTO,
//     VL_TETO_SEQUESTRO,
//     RE_SEQUESTRO,



// FATO_APREENSOES DO SIGACrimHomologadas 2024:
CONCATENATE (FATO_APREENSOES)
LOAD Distinct
    AutoNumberHash128('SIGACrim'&'_'&ID_OPERACAO) AS [%APREENSOESKEY], 

    // IPL AS Caso, // estará no DIM_CASOS
    // IPL AS Caso_de_Operação, // estará na DIM_OPERACOES
//////////////// comentado pois incluído no [%KEY] ////////////////
    // "Proc. Identificação" 
    // ID_OPERACAO,
    // DT_DEFLAGRACAO as "Data da Apreensão",
    // YEAR(DT_DEFLAGRACAO) as "Ano da Apreensão",
    // MONTH(DT_DEFLAGRACAO) as  "Mês da Apreensão",
    // DT_HOMOLOGACAO as "Data da Homologação",
    // year(DT_HOMOLOGACAO) as "Ano da Homologação",
    // month(DT_HOMOLOGACAO) as "Mês da Homologação",
    
//////////////
// MÉTRICAS //
//////////////

// Valores dos sequestros realizados nas operações como soma dos itens apreendidos
    COALESCE(VL_TOTAL_SEQUESTRO,0) as "1+2+3+5.2 Sequestros e bloqueios (Sequestros Móveis e Imóveis + Criptoativos + Bloqueio Financeiro)",
    COALESCE(VL_SEQUESTRO_VALOR_MOVEIS,0) AS "1 Valor Bens Imóveis Apreendidos/Sequestrados LVL1",
    COALESCE(VL_SEQUESTRO_VALOR_ESTIMADO_IMOVEIS,0) AS "2 Valor Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1",
    COALESCE(VL_SEQUESTRO_VALOR_CRIPTO,0) AS "3 Valor Criptoativos apreendidos/sequestrados LVL1",
    COALESCE(VL_SEQUESTRO_VALOR_BLOQUEADO_FINANCEIRO,0) AS "5 Valores Monetários Apreendidos/Sequestrados LVL1",
    ApplyMap('MapApreensoes_Maquinario_SIGACRIM_2024',ID_OPERACAO,0) AS "6 Valor Itens de Descapitalização Destruídos no Local LVL1",
    COALESCE(VL_TOTAL_SEQUESTRO,0) + ApplyMap('MapApreensoes_Maquinario_SIGACRIM_2024',ID_OPERACAO,'0') AS "Valor Total Descapitalização",
	COALESCE(VL_SEQUESTRO_VALOR_ESTIMADO_IMOVEIS,0) + COALESCE(VL_SEQUESTRO_VALOR_MOVEIS,0) AS "1+2 Bens Imóveis Apreendidos/Sequestrados + Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1",    
	COALESCE(VL_SEQUESTRO_VALOR_BLOQUEADO_FINANCEIRO,0) AS "5.2 Valores Monetários bloqueados via Bacenjud ou similares LVL2",
    COALESCE(VL_SEQUESTRO_VALOR_BLOQUEADO_FINANCEIRO,0) AS "4+5 Valores Monetários, Títulos e Direitos Apreendidos/Sequestrados LVL1",
    VL_TETO_SEQUESTRO // Número
RESIDENT TEMP_SIGACrimHomologadas
where YEAR(DT_DEFLAGRACAO) = 2024
;

// LINK TABLE DA FATO_APREENSOES DO SIGACrimHomologadas 2024
// CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM:
LOAD Distinct
    AutoNumberHash128("Proc. Identificação") AS [%CASOSKEY],
    AutoNumberHash128(ID_OPERACAO) AS [%OPERACOESKEY],
    AutoNumberHash128('SIGACrim'&'_'&ID_OPERACAO) AS [%APREENSOESKEY], 
//    NULL() AS [%CASOSDATAKEY],
//     NULL() AS [%EVENTOSKEY],
//     NULL() AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],
    
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128(ID_OPERACAO) AS [%ID_OPERACAO_KEY],
    AutoNumberHash128('SIGACrim'&'_'&ID_OPERACAO) AS [%GESTAO_BENS_ITEM_ID_KEY],
//    NULL() AS [%PROC_DATA_ID_KEY],
//    NULL() AS [%ID_EVENTOS_KEY],
//     NULL() AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY]
//
    // COMENTADO COM A NOVA MODELAGEM COM VÁRIAS KEYS 
    // IPL as [%Caso],
    // ETAPAOPERACAO,
    // IPL AS Caso, // estará no DIM_CASOS
    // IPL AS Caso_de_Operação, // estará na DIM_OPERACOES

    // Date(PRE_DT_PREVISTA_DEFLAGRACAO) as "Data Prevista para Deflagração",
    // YEAR(date(PRE_DT_PREVISTA_DEFLAGRACAO)) as "Ano Previsto para Deflagração",
    // MONTH(date(PRE_DT_PREVISTA_DEFLAGRACAO)) as "Mês Previsto para Deflagração",
//

//
// Considera a UNIDADE da OPERACAO do SIGACrimHomologadas como Unidade da Apreensão
// pois considera somente as descapitalizações registradas no SIGACrim em 2024
// antes das descapitalizações começarem a serem registradas no ePol
// Retirada a Unidade da Apreensão por erro da DIM_CASOS_APREENSAO_BENS que traz a unidade de custódia e não a de apreensão
// 	UNIDADE AS [%UNIDADE_KEY], // Texto
// 	UF AS "Unidade UF da Apreensão", // Texto
//     UNIDADE AS "Unidade Sigla da Apreensão", // Texto
//
	DATE(DT_DEFLAGRACAO) as Data,
    YEAR(DT_DEFLAGRACAO) as "Ano",
    MONTH(DT_DEFLAGRACAO) as  "Mês",
    Num(MONTH(DT_DEFLAGRACAO)) as "Mês (Num)",
    'Apreensão' as "Tipo da Data",
//
// COMENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
	// DT_DEFLAGRACAO as "Data da Apreensão",
    // YEAR(DT_DEFLAGRACAO) as "Ano da Apreensão",
    // MONTH(DT_DEFLAGRACAO) as  "Mês da Apreensão",
    'Apreensões SIGACrim' as "Fonte",
    'Apreensões' AS "Tipo do Fato"
    // ,
    // COMENTADO COM A NOVA MODELAGEM COM VÁRIAS KEYS 
    // Date(DT_HOMOLOGACAO) as "Data da Homologação",
    // YEAR(date(DT_HOMOLOGACAO)) as "Ano da Homologação",
    // MONTH(date(DT_HOMOLOGACAO)) as "Mês da Homologação",
    // Date(DT_DEFLAGRACAO) as "Data da Deflagração",
    // YEAR(date(DT_DEFLAGRACAO)) as "Ano da Deflagração",
    // MONTH(date(DT_DEFLAGRACAO)) as "Mês da Deflagração",
    // Num(MONTH(date(DT_DEFLAGRACAO))) as "Mês (Num) da Deflagração",

	// $(vCarregaUnidAreaDirCoorGeralDaOperacao)

RESIDENT TEMP_SIGACrimHomologadas
where YEAR(DT_DEFLAGRACAO) = 2024
;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM)
LOAD DISTINCT
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
	$(vCarregaUnidAreaDirCoorGeralDoCaso)
RESIDENT TEMP_DIM_CASOS;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM)
LOAD DISTINCT
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128("Proc_Data ID") AS [%CASOSDATAKEY],
    AutoNumberHash128("Proc_Data ID") AS [%PROC_DATA_ID_KEY]
RESIDENT TEMP_DIM_CASOS_DATA;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM)
// LOAD DISTINCT
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
//     AutoNumberHash128(id_ordem_original_evento) AS [%EVENTOSKEY],
//     AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY]
// RESIDENT TEMP_TABELAOEVENTOS_ID_UNIFICADO;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM)
// LOAD DISTINCT
//     AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
//     AutoNumberHash128(id_evento_apreensao) AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],
//     AutoNumberHash128(id_evento_apreensao) AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY]
// RESIDENT TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;

CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
Load
	*
RESIDENT TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM;

DROP TABLE TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_APREENSOES_SIGACRIM;
