TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando FATO_CASOS do TEMP_DIM_CASOS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
////////////////////////////////////////////////////////////////
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF  //
// FATO_CASOS DO DIM_CASOS                                    //
////////////////////////////////////////////////////////////////

// === FATO_CASOS DO DIM_CASOS === //
FATO_CASOS:
LOAD DISTINCT
    *,
    IF(
        "É Flagrante de Iniciativa Interna" = 'Sim', // Texto com 3 caracteres ('Sim' ou 'Não')
        'Não',
        'Sim'
    ) AS "É Flagrante de Iniciativa Externa"; // Texto com 3 caracteres ('Sim' ou 'Não')

LOAD Distinct
    AutoNumberHash128("Proc. Identificação") AS [%CASOSKEY],

///////////////////
// Sinalizadores //
///////////////////

    "Proc. Situação", // Texto com 12 caracteres ('em andamento' ou 'encerrado')
    "Proc. Instauração Tipo", // Texto com 9 caracteres ('portaria' ou 'flagrante')
    "Proc. Iniciativa Tipo", // Texto com 7 caracteres ('externa' ou 'interna')
    "Proc. Sigiloso", // Texto com 12 caracteres ('sigiloso' ou 'não sigiloso')
    "Proc. Autoria Identificada", // Número Real (1 ou 0)
    "Proc. Não Crime", // Número Real (1 ou 0)
    "Proc. Perícia", // Número Real (0 ou 1 ou 0)
    "Proc. Laudo Conclusivo", // Número Real (0 ou 1 ou 0)
    "Proc. Cooperação Jurídica Internacional", // Número Real (1 ou 0)
    "Proc. Cooperação Policial Internacional", // Número Real (1 ou 0)
    "Proc. Tipo", // Texto com 3 caracteres (9 registros distintos) (sem registros faltantes)
    "Proc. Sistema", // Texto com 7 caracteres ('epol' ou 'siscart') (sem registros faltantes)
    "Proc. Tem Preso", // Texto com 3 caracteres ('sim' ou 'não')
    "Proc. Prometheus", // Texto com 3 caracteres ('sim')
    "Proc. Migração Sinpro", // Número Real (1 ou 0) (sem registros faltantes)
    "Proc. Teve Cota", // Texto com 3 caracteres ('sim' ou 'não') (sem registros faltantes)
    "Proc. Relatado", // Texto com 3 caracteres ('sim' ou 'não') (sem registros faltantes)
    // "Proc. Retombado", // Texto com 3 caracteres ('sim' ou 'não')
	"Foi Instaurado por Flagrante", // Texto com 3 caracteres ('Sim' ou 'Não')
	"Foi Instaurado por TC", // Texto com 3 caracteres ('Sim' ou 'Não')
    IF(
        APPLYMAP('MapIdEventoTabelaoEventosPF', "Proc. Identificação", 'Não Encontrado') <> 'Não Encontrado',
        IF(
            YEAR(APPLYMAP('MapDtEventoTabelaoEventosPF', "Proc. Identificação", 'Não Encontrado')) = YEAR(DATE("Proc. Data Instauração")),
             'Sim',
             'Não'	
        )               
    ) AS "É Evento de Execução Direta", // Texto com 3 caracteres ('Sim' ou 'Não')

	IF(
        [Proc. Instauração Tipo] = 'Flagrante',
        IF(
            MATCH([Proc. Tipo], 'FLA','IPL')>0,
            IF(
                APPLYMAP('MapIdEventoTabelaoEventosPF', "Proc. Identificação", 'Não Encontrado') <> 'Não Encontrado',
                IF(
                    Year(APPLYMAP('MapDtEventoTabelaoEventosPF', "Proc. Identificação",0)) = Year(DATE("Proc. Data Instauração")),

                        'Sim',
                        'Não'

                )       
            )
        )       
    ) AS "É Flagrante de Iniciativa Interna", // Texto com 3 caracteres ('Sim' ou 'Não')
    
    // IF(
    //     [Proc. Instauração Tipo] = 'Flagrante',
    //     IF(
    //         MATCH([Proc. Tipo], 'FLA','IPL')>0,
    //         IF(
    //             APPLYMAP('MapIdEventoTabelaoEventosPF', "Proc. Identificação", 'Não Encontrado') = 'Não Encontrado',
    //             'Sim',
    //             'Não'     
    //         )
    //     )       
    // ) AS "É Flagrante de Iniciativa Externa", // Texto com 3 caracteres ('Sim' ou 'Não')

	"É Unidade de Fronteira do Caso", // Texto com 3 caracteres ('Sim' ou 'Não')

	"É Unidade de Estado Fronteiriço do Caso", // Texto com 3 caracteres ('Sim' ou 'Não')

//////////////// comentado pois incluído no [%CASOSKEY] ////////////////
    /// "Proc. Identificação", // Chave candidata em texto com 33 caracteres (sem registros faltantes)



    // "Proc. Data Recebimento", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Cadastro", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Parecer", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Distribuição", // Data (DD/MM/AAAA) como Texto com 10 caracteres


    /// "Proc. Data Instauração", // Data (DD/MM/AAAA) como Texto com 10 caracteres (sem registros faltantes)
    /// "Proc. Data Relatório", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    /// "Proc. Data Fato", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Vencimento", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Cota", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    "Proc. Quantidade Foro Privilegiado", // Número Real contendo 1 ou 0
    "Proc. Procurados Abertos", // Número Real
    "Proc. TC Quantidade Autores", // Número Real
    "Proc. Valor a Apurar", // Moeda r$ como Texto com 24 caracteres
    "Proc. Quantidade Indiciados", // Número Real
    "Proc. Quantidade Presos Siscart", // Número Real
    "Proc. Quantidade Mandado Prisão", // Número Real
    "Proc. Quantidade Mandado Busca", // Número Real
    "Proc. Valor Apurado", // Moeda r$ como Texto com 20 caracteres

    /// "Proc. Data Encerrado", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Decisão", // Timestamp (DD/MM/AAAA HH:MM:SS.SS) como Texto com 26 caracteres
    // "Proc. Data Última Movimentação Temp", // Data (DD/MM/AAAA) como Texto com 10 caracteres

    // "Proc. Data Retombamento", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Peça Relatório", // Data (DD/MM/AAAA) como Texto com 10 caracteres

    // "Proc. Data Último Retorno Externo", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Reabertura", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Suspensão", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Tarefa Pendente Temp",  // Data (DD/MM/AAAA) como Texto com 10 caracteres
    "Proc. Duração Dias", // Número como Texto com 19 caracteres
    /// "Proc. Data Instauração Ano", // Número Real
    /// "Proc. Data Instauração Mês", // Texto com 3 caracteres (12 registros distintos) (sem registros faltantes)
    /// "Proc. Data Instauração Dia", // Número Real
    /// "Proc. Data Relatório Ano", // Número Real
    /// "Proc. Data Relatório Mês", // Texto com 3 caracteres (12 registros distintos)
    /// "Proc. Data Relatório Dia", // Número Real
    /// "Proc. Data Encerrado Ano", // Número Real
    /// "Proc. Data Encerrado Mês", // Texto com 3 caracteres (12 registros distintos)
    /// "Proc. Data Encerrado Dia", // Número Real
    /// "Proc. Data Decisão Ano", // Número Real
    /// "Proc. Data Decisão Mês", // Texto com 3 caracteres (12 registros distintos)
    /// "Proc. Data Decisão Dia", // Número Real
    /// "Proc. Data Fato Ano", // Número Real
    /// "Proc. Data Fato Mês", // Texto com 3 caracteres (12 registros distintos)
    /// "Proc. Data Fato Dia", // Número Real

    /// "Proc. Data Última Movimentação", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    // "Proc. Data Retombamento Ano", // Número Real
    // "Proc. Data Retombamento Mês", // Texto com 3 caracteres (12 registros distintos)
    // "Proc. Data Retombamento Dia", // Número Real
    "Proc. Total Matéria Registro Especial", // Número Real
    "Proc. Quantidade Conduzidos", // Número Real (Presos Conduzidos podem ser conduzidos
                                   // - por TC, quando não serão presos, ou 
                                   // - por Flagrante, quando podem ou não serem presos)
    /// "Proc. Data Último Despacho", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    /// "Proc. Data Tarefa Pendente", // Data (DD/MM/AAAA) como Texto com 10 caracteres
    "Proc. Quantidade Presos", // Número Real (Total de Presos. Soma dos Flagrante e Capturados)
    "Proc. Quantidade Presos Flagrante", // Número Real (Presos em Flagrante)
    "Proc. Quantidade Presos Capturados", // Número Real (Presos Capturados não são Conduzidos)
    "Proc. Quantidade Conduzidos TC" // Número Real (Presos Conduzidos por TC não são Presos, mas sempre serão Presos Conduzidos)
RESIDENT TEMP_DIM_CASOS;


// === LINK TABLE DA FATO_CASOS DO DIM_CASOS === //
// CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS:
LOAD Distinct
    AutoNumberHash128("Proc. Identificação") AS [%CASOSKEY],
//     NULL() AS [%OPERACOESKEY],
//     NULL() AS [%APREENSOESKEY], 
//    NULL() AS [%CASOSDATAKEY],
//    NULL() AS [%EVENTOSKEY],
//     NULL() AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],
    
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
//     NULL() AS [%ID_OPERACAO_KEY],
//     NULL() AS [%GESTAO_BENS_ITEM_ID_KEY],
//    NULL() AS [%PROC_DATA_ID_KEY],
//    NULL() AS [%ID_EVENTOS_KEY],
//     NULL() AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY]

// Será inserido como Join abaixo
    // NULL() AS [%ID_OPERACAO],
// Será inserido como Join abaixo
    // NULL() AS [%GESTAO_BENS_ITEM_ID],
//
    // "Procedimento ID" AS [%PROCEDIMENTO_ID], // Chave primária em texto com 24 caracteres (sem registros faltantes)
// COMENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
    // $(vCarregaDatasDaCasos),
    Date([Proc. Data Instauração]) as Data,
    YEAR(date([Proc. Data Instauração])) as "Ano",
    MONTH(date([Proc. Data Instauração])) as "Mês",
    Num(MONTH(date([Proc. Data Instauração]))) as "Mês (Num)",
    'Instauração do Caso' as "Tipo da Data",
//
    'Casos ePol' as "Fonte",
    'Casos' AS "Tipo do Fato",
    
	$(vCarregaUnidAreaDirCoorGeralDoCaso)

RESIDENT TEMP_DIM_CASOS;

// CONCATENATE(TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS)
// LOAD Distinct
//     AutoNumberHash128("Proc. Identificação") AS [%CASOSKEY],
// //     NULL() AS [%OPERACOESKEY],
// //     NULL() AS [%APREENSOESKEY], 
// //    NULL() AS [%CASOSDATAKEY],
// //    NULL() AS [%EVENTOSKEY],
    
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
// //     NULL() AS [%ID_OPERACAO_KEY],
// //     NULL() AS [%GESTAO_BENS_ITEM_ID_KEY],
// //    NULL() AS [%PROC_DATA_ID_KEY],
// //    NULL() AS [%ID_EVENTOS_KEY],

// // Será inserido como Join abaixo
//     // NULL() AS [%ID_OPERACAO],
// // Será inserido como Join abaixo
//     // NULL() AS [%GESTAO_BENS_ITEM_ID],
// //
//     // "Procedimento ID" AS [%PROCEDIMENTO_ID], // Chave primária em texto com 24 caracteres (sem registros faltantes)
// // COMENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
//     // $(vCarregaDatasDaCasos),
//     Date([Proc. Data Relatório]) as Data,
//     YEAR(date([Proc. Data Relatório])) as "Ano",
//     MONTH(date([Proc. Data Relatório])) as "Mês",
//     Num(MONTH(date([Proc. Data Relatório]))) as "Mês (Num)",
//     'Relatório do Caso' as "Tipo da Data",
// //
//     'Casos ePol' as "Fonte",
//     'Casos' AS "Tipo do Fato",
    
// 	$(vCarregaUnidAreaDirCoorGeralDoCaso)

// RESIDENT TEMP_DIM_CASOS;



LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS)
LOAD DISTINCT
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128(ID_OPERACAO) AS [%OPERACOESKEY],
    AutoNumberHash128(ID_OPERACAO) AS [%ID_OPERACAO_KEY]
RESIDENT TEMP_SIGACrimHomologadas;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS)
LOAD DISTINCT
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128("GestãoBens Item ID") AS [%APREENSOESKEY], 
    AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%SUBCLASSESKEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%EVENTOSKEY],
    AutoNumberHash128("GestãoBens Item ID") AS [%GESTAO_BENS_ITEM_ID_KEY],
    AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%ITEM_SUBCLASSE_KEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY]
RESIDENT TEMP_DIM_CASOS_APREENSAO_BENS;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS)
LOAD DISTINCT
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128("Proc_Data ID") AS [%CASOSDATAKEY],
    AutoNumberHash128("Proc_Data ID") AS [%PROC_DATA_ID_KEY]
RESIDENT TEMP_DIM_CASOS_DATA;


CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
Load
	*
RESIDENT TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS;

DROP TABLE TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_FATO_CASOS;

CALL StoreAndDrop('FATO_CASOS', '$(vCaminhoTransformadosV3)');

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga FATO_CASOS do TEMP_DIM_CASOS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
