TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando FATO_EVENTOS_OPERACIONAIS;
TRACE >>>do TEMP_TABELAOEVENTOS_ID_UNIFICADO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
///////////////////////////////////////////////////////////////
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF //
// FATO EVENTOS DO tabelaoeventos.qvd COM LINK TABLE //
///////////////////////////////////////////////////////////////

// === FATO_EVENTOS DO tabelaoeventos.qvd === //
FATO_EVENTOS_OPERACIONAIS:
LOAD DISTINCT
    AutoNumberHash128(id_ordem_original_evento) AS [%EVENTOSKEY],

///////////////////
// Sinalizadores //
///////////////////

    houve_apreensao, // Boleano sim/não
    houve_prisao, // Boleano sim/não

//////////////
// Métricas //
//////////////

        qtd_presos // Número inteiro

RESIDENT TEMP_TABELAOEVENTOS_ID_UNIFICADO;


// === LINK TABLE DA FATO_EVENTOS DO tabelaoeventos.qvd ===
// CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS:
LOAD Distinct
    AutoNumberHash128("Proc. Identificação") AS [%CASOSKEY],
    AutoNumberHash128(ID_OPERACAO) AS [%OPERACOESKEY],
//     NULL() AS [%APREENSOESKEY], 
//     NULL() AS AS [%CASOSDATAKEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%EVENTOSKEY],
//     NULL() AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],
    
    
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128(ID_OPERACAO) AS [%ID_OPERACAO_KEY],
//     NULL() AS [%GESTAO_BENS_ITEM_ID_KEY],
//     NULL() AS [%PROC_DATA_ID_KEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
//     NULL() AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY]


//
// COMENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
//     Date(PRE_DT_PREVISTA_DEFLAGRACAO) as "Data Prevista para Deflagração",
//     YEAR(date(PRE_DT_PREVISTA_DEFLAGRACAO)) as "Ano Previsto para Deflagração",
//     MONTH(date(PRE_DT_PREVISTA_DEFLAGRACAO)) as "Mês Previsto para Deflagração",
// //
//     Date(DT_DEFLAGRACAO) as "Data da Deflagração",
//     YEAR(date(DT_DEFLAGRACAO)) as "Ano da Deflagração",
//     MONTH(date(DT_DEFLAGRACAO)) as "Mês da Deflagração",
//     Num(MONTH(date(DT_DEFLAGRACAO))) as "Mês (Num) da Deflagração",
// //
//     date(DT_INICIO) as "Data de Início",
//     Date(DT_HOMOLOGACAO) as "Data da Homologação",
//     YEAR(date(DT_HOMOLOGACAO)) as "Ano da Homologação",
//     MONTH(date(DT_HOMOLOGACAO)) as "Mês da Homologação",
//
    Date(dt_evento) as Data,
    YEAR(date(dt_evento)) as "Ano",
    MONTH(date(dt_evento)) as "Mês",
    Num(MONTH(date(dt_evento))) as "Mês (Num)",
    'Evento Operacional' as "Tipo da Data",
//
    'Eventos Operacionais SIGACrim' as "Fonte",
    'Eventos Operacionais' AS "Tipo do Fato"
    
	,$(vCarregaUnidAreaDirCoorGeralDoEventoOperacional)

RESIDENT TEMP_TABELAOEVENTOS_ID_UNIFICADO;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS)
LOAD DISTINCT
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
	$(vCarregaUnidAreaDirCoorGeralDoCaso)
RESIDENT TEMP_DIM_CASOS;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS)
LOAD DISTINCT
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
    AutoNumberHash128("GestãoBens Item ID") AS [%APREENSOESKEY], 
    AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%SUBCLASSESKEY],
    AutoNumberHash128("GestãoBens Item ID") AS [%GESTAO_BENS_ITEM_ID_KEY],
    AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%ITEM_SUBCLASSE_KEY]
RESIDENT TEMP_DIM_CASOS_APREENSAO_BENS;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS)
LOAD DISTINCT
    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
    AutoNumberHash128(id_evento_apreensao) AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],
    AutoNumberHash128(id_evento_apreensao) AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY]
RESIDENT TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;

LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS)
LOAD DISTINCT
    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
    AutoNumberHash128(id_evento_prisao) AS [%EVENTOSPRISOESEXTERNASESTRANGEIRASKEY],
    AutoNumberHash128(id_evento_prisao) AS [%ID_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRAS_KEY]
RESIDENT TEMP_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRO;

CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
Load
	*
RESIDENT TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS;

DROP TABLE TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_OPERACIONAIS;

CALL StoreAndDrop('FATO_EVENTOS_OPERACIONAIS', '$(vCaminhoTransformadosV3)');

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga FATO_EVENTOS_OPERACIONAIS;
TRACE >>>do TEMP_TABELAOEVENTOS_ID_UNIFICADO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
