TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando FATO_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;
TRACE >>> do TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
///////////////////////////////////////////////////////////////
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF //
// FATO_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO DO Eventos_prisoes.qvd COM LINK TABLE //
///////////////////////////////////////////////////////////////

// === FATO_EVENTOS_APREENSOES DO Eventos_apreensoes.qvd === //
FATO_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO:
LOAD
    AutoNumberHash128(id_evento_apreensao) AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],
//     nr_caso,
//     id_evento,
//     id_evento_apreensao,
//     "GestãoBens Item Material Subclasse Código",
//     cd_item_epol_fk,
//     cd_categoria_epol_fk,
//     cd_classe_epol_fk,
//     nr_apreensao,
//     dt_apreensao,
//     ds_apreensao,
//     ds_item,
    qt_item,
    st_selecionado
//     ,
//     ds_local_apreensao,
//     un_item
//     ,
//     "Proc. Identificação"
RESIDENT TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;


// === LINK TABLE DA FATO_EVENTOS_APREENSOES DO Eventos_apreensoes.qvd ===
// CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO:
LOAD Distinct
//     NULL() AS [%CASOSKEY],
//     NULL() AS [%OPERACOESKEY],
//     NULL() AS [%APREENSOESKEY], 
    AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%SUBCLASSESKEY],
//     NULL() AS [%CASOSDATAKEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%EVENTOSKEY],
    AutoNumberHash128(id_evento_apreensao) AS [%EVENTOSAPREENSOESEXTERNASESTRANGEIRASKEY],

//     NULL() AS [%PROC_IDENTIFICACAO_KEY],
//     NULL() AS [%ID_OPERACAO_KEY],
//     NULL() AS [%GESTAO_BENS_ITEM_ID_KEY],
    AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%ITEM_SUBCLASSE_KEY],
//     NULL() AS [%PROC_DATA_ID_KEY],
    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
    AutoNumberHash128(id_evento_apreensao) AS [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY],
    
//
// COMENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
//     Date(PRE_DT_PREVISTA_DEFLAGRACAO) as "Data Prevista para Deflagração",
//     YEAR(date(PRE_DT_PREVISTA_DEFLAGRACAO)) as "Ano Previsto para Deflagração",
//     MONTH(date(PRE_DT_PREVISTA_DEFLAGRACAO)) as "Mês Previsto para Deflagração",
// //
//     Date(DT_DEFLAGRACAO) as "Data da Deflagração",
//     YEAR(date(DT_DEFLAGRACAO)) as "Ano da Deflagração",
//     MONTH(date(DT_DEFLAGRACAO)) as "Mês da Deflagração",
//     Num(MONTH(date(DT_DEFLAGRACAO))) as "Mês (Num) da Deflagração",
// //
//     date(DT_INICIO) as "Data de Início",
//     Date(DT_HOMOLOGACAO) as "Data da Homologação",
//     YEAR(date(DT_HOMOLOGACAO)) as "Ano da Homologação",
//     MONTH(date(DT_HOMOLOGACAO)) as "Mês da Homologação",
//
    Date(dt_apreensao) as Data,
    YEAR(date(dt_apreensao)) as "Ano",
    MONTH(date(dt_apreensao)) as "Mês",
    Num(MONTH(date(dt_apreensao))) as "Mês (Num)",
    'Evento Apreensão Externo/Estrangeiro' as "Tipo da Data",
//
    'Eventos Apreensões SIGACrim' as "Fonte",
    'Eventos Apreensões Externos/Estrangeiros' AS "Tipo do Fato"
    
    // CARREGA %UNIDADEKEY
    ,$(vCarregaUnidAreaDirCoorGeralDoEventoExternoEstrangeiro)

RESIDENT TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO)
// LOAD DISTINCT
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
// 	$(vCarregaUnidAreaDirCoorGeralDoCaso)
// RESIDENT TEMP_DIM_CASOS;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO)
// LOAD DISTINCT
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
//     AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
//     AutoNumberHash128("GestãoBens Item ID") AS [%APREENSOESKEY], 
//     AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%SUBCLASSESKEY],
//     AutoNumberHash128("GestãoBens Item ID") AS [%GESTAO_BENS_ITEM_ID_KEY],
//     AutoNumberHash128("GestãoBens Item Material Subclasse Código") AS [%ITEM_SUBCLASSE_KEY]
// RESIDENT TEMP_DIM_CASOS_APREENSAO_BENS;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO)
// LOAD DISTINCT
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
//     AutoNumberHash128("Proc_Data ID") AS [%CASOSDATAKEY],
//     AutoNumberHash128("Proc_Data ID") AS [%PROC_DATA_ID_KEY]
// RESIDENT TEMP_DIM_CASOS_DATA;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO)
// LOAD DISTINCT
//     AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
//     AutoNumberHash128(ID_OPERACAO) AS [%OPERACOESKEY],
//   AutoNumberHash128(ID_OPERACAO) AS [%ID_OPERACAO_KEY]
// RESIDENT TEMP_SIGACrimHomologadas;

// LEFT JOIN (TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_OPERACOES_SIGACRIM)
// LOAD DISTINCT
//    AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY],
//     AutoNumberHash128(id_ordem_original_evento) AS [%EVENTOSKEY],
//     AutoNumberHash128(id_ordem_original_evento) AS [%ID_EVENTOS_KEY]
// RESIDENT TEMP_TABELAOEVENTOS_ID_UNIFICADO;

CONCATENATE(LINK_TABLE_APREENSOES_OPERACOES_CASOS)
Load
	*
RESIDENT TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;

DROP TABLE TEMP_LINK_TABLE_APREENSOES_OPERACOES_CASOS_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;

CALL StoreAndDrop('FATO_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO', '$(vCaminhoTransformadosV3)');

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga FATO_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;
TRACE >>> do TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
