TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Iniciando carga das Medidas Mestras do Epol;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

// Variáveis de medidas mestras em cada tela do APP

/*******************************************************************************
    OBS: 
    - as variáveis de medida mestra que terminam sem 'Tot' deve ser usadas
    nos gráficos que usam dimensões de Unidade ou localizações etc.
    - as variáveis de medida mestra que terminam com 'Tot' deve ser usadas
    nos gráficos que usam dimensões de Data Mês Ano etc. DATA=*TOT
*******************************************************************************/

//-----------------------------------------------------------------------------------------------
// Medidas Mestras de Inquéritos
//-----------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------
// Variáveis auxiliares de seleção de data (evita repetição de GetSelectedCount em todo o script)
//-----------------------------------------------------------------------------------------------
SET vTemSelecaoDatasContextoFato =
    GetSelectedCount([Ano da Deflagração])
    + GetSelectedCount([Mês da Deflagração])
    + GetSelectedCount([Data da Deflagração])
    + GetSelectedCount([Ano da Apreensão])
    + GetSelectedCount([Mês da Apreensão])
    + GetSelectedCount([Data da Apreensão])
    + GetSelectedCount([Proc_Data Data Ano])
    + GetSelectedCount([Proc_Data Data Mês])
    + GetSelectedCount([Proc_Data Data])
    + GetSelectedCount([Ano do Cadastro])
    + GetSelectedCount([Mês do Cadastro])
    + GetSelectedCount([Data do Cadastro])
    + GetSelectedCount([Ano da Instauração])
    + GetSelectedCount([Mês da Instauração])
    + GetSelectedCount([Data da Instauração])
    + GetSelectedCount([Ano do Relatório])
    + GetSelectedCount([Mês do Relatório])
    + GetSelectedCount([Data do Relatório]) > 0
;

SET vTemSelecaoDatasCalendario =
    GetSelectedCount([Ano])
    + GetSelectedCount([Mês])
    + GetSelectedCount([Data]) > 0
;

SET vTemSelecaoAnoCalendario =
    GetSelectedCount([Ano]) > 0
;

SET vTemSelecaoMesOuDataCalendario =
    GetSelectedCount([Mês]) + GetSelectedCount([Data]) > 0
;

SET vTemSelecaoAnoProcData =
    GetSelectedCount([Proc_Data Data Ano]) > 0
;

SET vTemSelecaoMesOuDataProcData =
    GetSelectedCount([Proc_Data Data Mês]) + GetSelectedCount([Proc_Data Data]) > 0
;

//-----------------------------------------------------------------------------------------------
// SUBs geradores - etapa 1 de parametrização do ePol
//-----------------------------------------------------------------------------------------------

SUB GerarMedidasMestrasEpolProcData6(pAlias, pRadical)
    SET vMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)ProcDtDtMesAno),
                $($(pRadical)ProcDtDtMesAnoPorEfet),
                $($(pRadical)PfEmNumProcDtDtMesAno)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfet),
                $($(pRadical)PfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias));

    SET vMedidaMestra$(pAlias)Tot =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)ProcDtDtMesAno),
                $($(pRadical)ProcDtDtMesAnoPorEfetTot),
                $($(pRadical)PfEmNumProcDtDtMesAno)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfetTot),
                $($(pRadical)PfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias)Tot);

    SET vMedidaMestra$(pAlias)SomAnter =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SomAnterProcDtDtMesAno),
                $($(pRadical)SomAnterProcDtDtMesAno),
                $($(pRadical)SomAnterPfEmNumProcDtDtMesAno)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterPfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias)SomAnter);

    SET vMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfet),
                $($(pRadical)PfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)ProcDtDtMesAno),
                    $($(pRadical)ProcDtDtMesAnoPorEfet),
                    $($(pRadical)PfEmNumProcDtDtMesAno)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)AnoAtual),
                    $($(pRadical)AnoAtualPorEfet),
                    $($(pRadical)PfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias));

    SET vMedidaMestraKpi$(pAlias)Tot =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfetTot),
                $($(pRadical)PfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)ProcDtDtMesAno),
                    $($(pRadical)ProcDtDtMesAnoPorEfetTot),
                    $($(pRadical)PfEmNumProcDtDtMesAno)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)AnoAtual),
                    $($(pRadical)AnoAtualPorEfetTot),
                    $($(pRadical)PfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias)Tot);

    SET vMedidaMestraKpi$(pAlias)SomAnter =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterPfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)SomAnterProcDtDtMesAno),
                    $($(pRadical)SomAnterProcDtDtMesAno),
                    $($(pRadical)SomAnterPfEmNumProcDtDtMesAno)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)SomAnterAnoAtual),
                    $($(pRadical)SomAnterAnoAtual),
                    $($(pRadical)SomAnterPfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias)SomAnter);
END SUB

SUB GerarMedidasMestrasEpolInstauracao6(pAlias, pRadical)
    SET vMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAnoInst),
                $($(pRadical)DtMesAnoInstPorEfet),
                $($(pRadical)PfEmNumDtMesAnoInst)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfet),
                $($(pRadical)PfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias));

    SET vMedidaMestra$(pAlias)Tot =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAnoInst),
                $($(pRadical)DtMesAnoInstPorEfetTot),
                $($(pRadical)PfEmNumDtMesAnoInst)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfetTot),
                $($(pRadical)PfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias)Tot);

    SET vMedidaMestra$(pAlias)SomAnter =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SomAnterDtMesAnoInst),
                $($(pRadical)SomAnterDtMesAnoInst),
                $($(pRadical)SomAnterPfEmNumDtMesAnoInst)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterPfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias)SomAnter);

    SET vMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfet),
                $($(pRadical)PfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)DtMesAnoInst),
                    $($(pRadical)DtMesAnoInstPorEfet),
                    $($(pRadical)PfEmNumDtMesAnoInst)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)AnoAtual),
                    $($(pRadical)AnoAtualPorEfet),
                    $($(pRadical)PfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias));

    SET vMedidaMestraKpi$(pAlias)Tot =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAnoPorEfetTot),
                $($(pRadical)PfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)DtMesAnoInst),
                    $($(pRadical)DtMesAnoInstPorEfetTot),
                    $($(pRadical)PfEmNumDtMesAnoInst)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)AnoAtual),
                    $($(pRadical)AnoAtualPorEfetTot),
                    $($(pRadical)PfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias)Tot);

    SET vMedidaMestraKpi$(pAlias)SomAnter =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterDtMesAno),
                $($(pRadical)SomAnterPfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)SomAnterDtMesAnoInst),
                    $($(pRadical)SomAnterDtMesAnoInst),
                    $($(pRadical)SomAnterPfEmNumDtMesAnoInst)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)SomAnterAnoAtual),
                    $($(pRadical)SomAnterAnoAtual),
                    $($(pRadical)SomAnterPfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias)SomAnter);
END SUB

SUB GerarTitulosERodapeEpolProcData(pAlias, pTituloAbs, pTituloEfet, pTituloPf, pRadical)
    SET vTituloMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloEfet) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloEfet) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloEfet) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloEfet) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloEfet) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloEfet) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloEfet) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloEfet) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) em ' & '@(=Year(Today()))',
                            '$(pTituloEfet) em ' & '@(=Year(Today()))',
                            '$(pTituloPf) em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                'em ' & @(vAnoSelecionado),
                'por Efetivo em ' & @(vAnoSelecionado),
                'PF EM NÚMEROS em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    'de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'por Efetivo de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        'em ' & @(vProcDataDataAnoSelecionado),
                        'por Efetivo em ' & @(vProcDataDataAnoSelecionado),
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'por Efetivo de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'em ' & '@(=Year(Today()))',
                            'por Efetivo em ' & '@(=Year(Today()))',
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));

    SET vRodapeMedidaMestra$(pAlias) =
        'Ano anterior: '
        &
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)ProcDtDtAnoAnterior),
                $($(pRadical)ProcDtDtAnoAnteriorPorEfet),
                $($(pRadical)PfEmNumProcDtDtAnoAnterior)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)AnoAnterior),
                $($(pRadical)AnoAnteriorPorEfet),
                $($(pRadical)PfEmNumAnoAnterior)
            )
        )
    ;

    CALL TratarExpansaoMacro(vRodapeMedidaMestra$(pAlias));
END SUB

SUB GerarTitulosERodapeEpolInstauracao(pAlias, pTituloAbs, pTituloEfet, pTituloPf, pRadical)
    SET vTituloMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloEfet) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloEfet) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloEfet) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloEfet) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloEfet) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloEfet) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloEfet) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloEfet) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) em ' & '@(=Year(Today()))',
                            '$(pTituloEfet) em ' & '@(=Year(Today()))',
                            '$(pTituloPf) em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                'em ' & @(vAnoSelecionado),
                'por Efetivo em ' & @(vAnoSelecionado),
                'PF EM NÚMEROS em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    'de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'por Efetivo de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        'em ' & @(vProcDataDataAnoSelecionado),
                        'por Efetivo em ' & @(vProcDataDataAnoSelecionado),
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'por Efetivo de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'em ' & '@(=Year(Today()))',
                            'por Efetivo em ' & '@(=Year(Today()))',
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));

    SET vRodapeMedidaMestra$(pAlias) =
        'Ano anterior: '
        &
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)AnoAnteriorInst),
                $($(pRadical)AnoAnteriorInstPorEfet),
                $($(pRadical)PfEmNumAnoAnteriorInst)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)AnoAnterior),
                $($(pRadical)AnoAnteriorPorEfet),
                $($(pRadical)PfEmNumAnoAnterior)
            )
        )
    ;

    CALL TratarExpansaoMacro(vRodapeMedidaMestra$(pAlias));
END SUB

SUB GerarMedidasMestrasEpolSemRel4(pAlias, pRadical)
    SET vMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)),
                $($(pRadical)PorEfet),
                $($(pRadical)PfEmNum)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SemRelDtAprOpeCaso),
                $($(pRadical)SemRelDtAprOpeCasoPorEfet),
                $($(pRadical)PfEmNumSemRelDtAprOpeCaso)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias));

    SET vMedidaMestra$(pAlias)Tot =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)),
                $($(pRadical)PorEfetTot),
                $($(pRadical)PfEmNum)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SemRelDtAprOpeCaso),
                $($(pRadical)SemRelDtAprOpeCasoPorEfetTot),
                $($(pRadical)PfEmNumSemRelDtAprOpeCaso)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias)Tot);

    SET vMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)),
                $($(pRadical)PorEfet),
                $($(pRadical)PfEmNum)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SemRelDtAprOpeCaso),
                $($(pRadical)SemRelDtAprOpeCasoPorEfet),
                $($(pRadical)PfEmNumSemRelDtAprOpeCaso)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias));

    SET vMedidaMestraKpi$(pAlias)Tot =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)),
                $($(pRadical)PorEfetTot),
                $($(pRadical)PfEmNum)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)SemRelDtAprOpeCaso),
                $($(pRadical)SemRelDtAprOpeCasoPorEfetTot),
                $($(pRadical)PfEmNumSemRelDtAprOpeCaso)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias)Tot);
END SUB

SUB GerarMedidasMestrasEpolProcData2(pAlias, pRadical)
    SET vMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)ProcDtDtMesAno),
                $($(pRadical)ProcDtDtMesAno),
                $($(pRadical)PfEmNumProcDtDtMesAno)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAno),
                $($(pRadical)PfEmNumDtMesAno)
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias));

    SET vMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)DtMesAno),
                $($(pRadical)DtMesAno),
                $($(pRadical)PfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)ProcDtDtMesAno),
                    $($(pRadical)ProcDtDtMesAno),
                    $($(pRadical)PfEmNumProcDtDtMesAno)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)AnoAtual),
                    $($(pRadical)AnoAtual),
                    $($(pRadical)PfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias));
END SUB

SUB GerarMedidasDuracaoEpolSemRel2(pAlias, pRadical)
    SET vMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            $($(pRadical)),
            $($(pRadical)SemRelDtAprOpeCaso)
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestra$(pAlias));

    SET vMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoDatasContextoFato),
            $($(pRadical)),
            $($(pRadical)SemRelDtAprOpeCaso)
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias));
END SUB

SUB GerarMedidaSoPfKpiEpolProcData(pAlias, pRadical)
    SET vMedidaMestraKpi$(pAlias)SoPfEmNumeros =
        IF(
            $(vTemSelecaoDatasCalendario),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)PfEmNumDtMesAno),
                $($(pRadical)PfEmNumDtMesAno),
                $($(pRadical)PfEmNumDtMesAno)
            ),
            IF(
                $(vTemSelecaoDatasContextoFato),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)PfEmNumProcDtDtMesAno),
                    $($(pRadical)PfEmNumProcDtDtMesAno),
                    $($(pRadical)PfEmNumProcDtDtMesAno)
                ),
                PICK(
                    @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    $($(pRadical)PfEmNumAnoAtual),
                    $($(pRadical)PfEmNumAnoAtual),
                    $($(pRadical)PfEmNumAnoAtual)
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vMedidaMestraKpi$(pAlias)SoPfEmNumeros);
END SUB

SUB GerarTitulosEpolSemRelTimestamp3(pAlias, pTituloAbs, pTituloEfet, pTituloPf)
    SET vTituloMedidaMestra$(pAlias) =
        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
            '$(pTituloAbs) em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))',
            '$(pTituloEfet) em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))',
            '$(pTituloPf) em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))'
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
            '$(pTituloAbs) em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))',
            '$(pTituloEfet) em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))',
            '$(pTituloPf) em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))'
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
            'em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))',
            'por Efetivo em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))',
            'PF EM NÚMEROS em ' & '@(=Timestamp(ReloadTime(), 'DD/MM/YYYY hh:mm:ss'))'
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));
END SUB

SUB GerarTitulosEpolSemRelAnoAtual3(pAlias, pTituloAbs, pTituloEfet, pTituloPf)
    SET vTituloMedidaMestra$(pAlias) =
        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
            '$(pTituloAbs) em ' & '@(=Year(Today()))',
            '$(pTituloEfet) em ' & '@(=Year(Today()))',
            '$(pTituloPf) em ' & '@(=Year(Today()))'
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
            '$(pTituloAbs) em ' & '@(=Year(Today()))',
            '$(pTituloEfet) em ' & '@(=Year(Today()))',
            '$(pTituloPf) em ' & '@(=Year(Today()))'
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
            'em ' & '@(=Year(Today()))',
            'por Efetivo em ' & '@(=Year(Today()))',
            'PF EM NÚMEROS em ' & '@(=Year(Today()))'
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));
END SUB

SUB GerarTitulosEpolDuracaoSemRelAnoAtual(pAlias, pTituloPrincipal, pTituloCurto)
    SET vTituloMedidaMestra$(pAlias) =
        '$(pTituloPrincipal) em ' & '@(=Year(Today()))'
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        '$(pTituloPrincipal) em ' & '@(=Year(Today()))'
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        '$(pTituloCurto)'
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));
END SUB

SUB GerarTitulosERodapeEpolProcData2SemEfet(pAlias, pTituloAbs, pTituloPf, pRadical)
    SET vTituloMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) em ' & '@(=Year(Today()))',
                            '$(pTituloAbs) em ' & '@(=Year(Today()))',
                            '$(pTituloPf) em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                'em ' & @(vAnoSelecionado),
                'em ' & @(vAnoSelecionado),
                'PF EM NÚMEROS em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    'de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        'em ' & @(vProcDataDataAnoSelecionado),
                        'em ' & @(vProcDataDataAnoSelecionado),
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'em ' & '@(=Year(Today()))',
                            'em ' & '@(=Year(Today()))',
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));

    SET vRodapeMedidaMestra$(pAlias) =
        'Ano anterior: '
        &
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)ProcDtDtAnoAnterior),
                $($(pRadical)ProcDtDtAnoAnterior),
                $($(pRadical)PfEmNumProcDtDtAnoAnterior)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)AnoAnterior),
                $($(pRadical)AnoAnterior),
                $($(pRadical)PfEmNumAnoAnterior)
            )
        )
    ;

    CALL TratarExpansaoMacro(vRodapeMedidaMestra$(pAlias));
END SUB

SUB GerarTitulosERodapeEpolProcData2ComEfetRodapeDuplicado(pAlias, pTituloAbs, pTituloEfet, pTituloPf, pRadical)
    SET vTituloMedidaMestra$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloEfet) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloEfet) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloEfet) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloEfet) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                        '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestra$(pAlias));

    SET vTituloMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloAbs) em ' & @(vAnoSelecionado),
                '$(pTituloEfet) em ' & @(vAnoSelecionado),
                '$(pTituloPf) em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloAbs) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloEfet) de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPf) de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloAbs) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloEfet) em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPf) em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloEfet) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloPf) de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloAbs) em ' & '@(=Year(Today()))',
                            '$(pTituloEfet) em ' & '@(=Year(Today()))',
                            '$(pTituloPf) em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias));

    SET vTituloCurtoMedidaMestraKpi$(pAlias) =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                'em ' & @(vAnoSelecionado),
                'por Efetivo em ' & @(vAnoSelecionado),
                'PF EM NÚMEROS em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    'de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'por Efetivo de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        'em ' & @(vProcDataDataAnoSelecionado),
                        'por Efetivo em ' & @(vProcDataDataAnoSelecionado),
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'por Efetivo de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'em ' & '@(=Year(Today()))',
                            'por Efetivo em ' & '@(=Year(Today()))',
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias));

    SET vRodapeMedidaMestra$(pAlias) =
        'Ano anterior: '
        &
        IF(
            $(vTemSelecaoDatasContextoFato),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)ProcDtDtAnoAnterior),
                $($(pRadical)ProcDtDtAnoAnterior),
                $($(pRadical)PfEmNumProcDtDtAnoAnterior)
            ),
            PICK(
                @(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                $($(pRadical)AnoAnterior),
                $($(pRadical)AnoAnterior),
                $($(pRadical)PfEmNumAnoAnterior)
            )
        )
    ;

    CALL TratarExpansaoMacro(vRodapeMedidaMestra$(pAlias));
END SUB

SUB GerarTitulosSoPfKpiEpolProcData(pAlias, pTituloPrefixo)
    SET vTituloMedidaMestraKpi$(pAlias)SoPfEmNumeros =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                '$(pTituloPrefixo) PF EM NÚMEROS em ' & @(vAnoSelecionado),
                '$(pTituloPrefixo) PF EM NÚMEROS em ' & @(vAnoSelecionado),
                '$(pTituloPrefixo) PF EM NÚMEROS em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    '$(pTituloPrefixo) PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPrefixo) PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    '$(pTituloPrefixo) PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        '$(pTituloPrefixo) PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPrefixo) PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado),
                        '$(pTituloPrefixo) PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloPrefixo) PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloPrefixo) PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            '$(pTituloPrefixo) PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            '$(pTituloPrefixo) PF EM NÚMEROS em ' & '@(=Year(Today()))',
                            '$(pTituloPrefixo) PF EM NÚMEROS em ' & '@(=Year(Today()))',
                            '$(pTituloPrefixo) PF EM NÚMEROS em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloMedidaMestraKpi$(pAlias)SoPfEmNumeros);

    SET vTituloCurtoMedidaMestraKpi$(pAlias)SoPfEmNumeros =
        IF(
            $(vTemSelecaoAnoCalendario),
            PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                'PF EM NÚMEROS em ' & @(vAnoSelecionado),
                'PF EM NÚMEROS em ' & @(vAnoSelecionado),
                'PF EM NÚMEROS em ' & @(vAnoSelecionado)
            ),
            IF(
                $(vTemSelecaoMesOuDataCalendario),
                PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano]),
                    'PF EM NÚMEROS de ' & MIN([Ano]) & ' a '& MAX([Ano])
                ),
                IF(
                    $(vTemSelecaoAnoProcData),
                    PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado),
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado),
                        'PF EM NÚMEROS em ' & @(vProcDataDataAnoSelecionado)
                    ),
                    IF(
                        $(vTemSelecaoMesOuDataProcData),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano]),
                            'PF EM NÚMEROS de ' & MIN([Proc_Data Data Ano]) & ' a '& MAX([Proc_Data Data Ano])
                        ),
                        PICK(@(vMostrarValAbsouRelaoEfetouPfEmNum)+1,
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))',
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))',
                            'PF EM NÚMEROS em ' & '@(=Year(Today()))'
                        )
                    )
                )
            )
        )
    ;

    CALL TratarExpansaoMacro(vTituloCurtoMedidaMestraKpi$(pAlias)SoPfEmNumeros);
END SUB

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras das prisoes em flagrante relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra das prisoes em flagrante com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('PrisoesEmFlagrante', 'vPrisEmFlagr');
CALL GerarTitulosERodapeEpolProcData('PrisoesEmFlagrante', 'Prisões em Flagrante', 'Prisões em Flagrante por Efetivo', 'Prisões em Flagrante PF EM NÚMEROS', 'vPrisEmFlagr');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras das prisoes em flagrante internas relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra das prisoes em flagrante internas com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('PrisoesEmFlagranteInternas', 'vPrisEmFlagrInt');
CALL GerarTitulosERodapeEpolProcData('PrisoesEmFlagranteInternas', 'Prisões em Flagrante Internas', 'Prisões em Flagrante Internas por Efetivo', 'Prisões em Flagrante Internas PF EM NÚMEROS', 'vPrisEmFlagrInt');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras das prisoes em flagrante externas relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra das prisoes em flagrante externas com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('PrisoesEmFlagranteExternas', 'vPrisEmFlagrExt');
CALL GerarTitulosERodapeEpolProcData('PrisoesEmFlagranteExternas', 'Prisões em Flagrante Externas', 'Prisões em Flagrante Externas por Efetivo', 'Prisões em Flagrante Externas PF EM NÚMEROS', 'vPrisEmFlagrExt');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos instaurados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos instaurados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosInstaurados', 'vIplInst');
CALL GerarTitulosERodapeEpolProcData('InqueritosInstaurados', 'Inquéritos Instaurados', 'Inquéritos Instaurados por Efetivo', 'Inquéritos Instaurados PF EM NÚMEROS', 'vIplInst');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos instaurados por iniciativa própria relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos instaurados por iniciativa própria com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosInstauradosPorIniciativaPropria', 'vIplInstInicProp');
CALL GerarTitulosERodapeEpolProcData('InqueritosInstauradosPorIniciativaPropria', 'Inquéritos Instaurados por Iniciativa Própria ', 'Inquéritos Instaurados por Iniciativa Própria  por Efetivo', 'Inquéritos Instaurados por Iniciativa Própria  PF EM NÚMEROS', 'vIplInstInicProp');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos flagrantes instaurados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos flagrantes instaurados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolInstauracao6('FlagrantesInstaurados', 'vFlaInst');
CALL GerarTitulosERodapeEpolInstauracao('FlagrantesInstaurados', 'Flagrantes Instaurados', 'Flagrantes Instaurados por Efetivo', 'Flagrantes Instaurados PF EM NÚMEROS', 'vFlaInst');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos flagrantes instaurados internos relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos flagrantes instaurados internos com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolInstauracao6('FlagrantesInstauradosInternos', 'vFlaInstInt');
CALL GerarTitulosERodapeEpolInstauracao('FlagrantesInstauradosInternos', 'Flagrantes Instaurados Internos', 'Flagrantes Instaurados Internos por Efetivo', 'Flagrantes Instaurados Internos PF EM NÚMEROS', 'vFlaInstInt');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos flagrantes instaurados externos relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos flagrantes instaurados externos com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolInstauracao6('FlagrantesInstauradosExternos', 'vFlaInstExt');
CALL GerarTitulosERodapeEpolInstauracao('FlagrantesInstauradosExternos', 'Flagrantes Instaurados Externos', 'Flagrantes Instaurados Externos por Efetivo', 'Flagrantes Instaurados Externos PF EM NÚMEROS', 'vFlaInstExt');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos TCO instaurados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos TCO instaurados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolInstauracao6('TcoInstaurados', 'vTcoInst');

// Título da medida mestra dos TCO instaurados:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolInstauracao('TcoInstaurados', 'TCO Instaurados', 'TCO Instaurados por Efetivo', 'TCO Instaurados PF EM NÚMEROS', 'vTcoInst');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos TCOs encerrados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos TCOs encerrados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolInstauracao6('TcoEncerrados', 'vTcoEnce');

// Título da medida mestra dos TCOs encerrados:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolInstauracao('TcoEncerrados', 'TCO Encerrados', 'TCO Encerrados por Efetivo', 'TCO Encerrados PF EM NÚMEROS', 'vTcoEnce');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos relatados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos relatados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosRelatados', 'vIplRelat');
CALL GerarTitulosERodapeEpolProcData('InqueritosRelatados', 'Inquéritos Relatados', 'Inquéritos Relatados por Efetivo', 'Inquéritos Relatados PF EM NÚMEROS', 'vIplRelat');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos em andamento 
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos em andamento com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolSemRel4('InqueritosEmAndamento', 'vIplEmAnd');

// Título da medida mestra dos inquéritos em andamento:

// Títulos gerados por SUB (etapa 2):
CALL GerarTitulosEpolSemRelTimestamp3('InqueritosEmAndamento', 'Inquéritos Em Andamento', 'Inquéritos Em Andamento por Efetivo', 'Inquéritos Em Andamento PF EM NÚMEROS');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras da duração média dos inquéritos em andamento 
//-----------------------------------------------------------------------------------------------

// Medida mestra da duração média dos inquéritos em andamento com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasDuracaoEpolSemRel2('DuracaoMediaInqueritosEmAndamento', 'vDurMedIplEmAnd');

// Título da medida mestra da duração média dos inquéritos em andamento:

// Títulos gerados por SUB (etapa 2):
CALL GerarTitulosEpolDuracaoSemRelAnoAtual('DuracaoMediaInqueritosEmAndamento', 'Duração Média dos Inquéritos Em Andamento', 'em '' & ''@(=Year(Today()))');







//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras da duração média dos inquéritos relatados:
//-----------------------------------------------------------------------------------------------

// Medida mestra da duração média dos inquéritos relatados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('DuracaoMediaInqueritosRelatados', 'vDurMedIplRela');

// Título da medida mestra da duração média dos inquéritos relatados:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2ComEfetRodapeDuplicado('DuracaoMediaInqueritosRelatados', 'Duração Média dos Inquéritos Relatados', 'Duração Média dos Inquéritos Relatados por Efetivo', 'Duração Média dos Inquéritos Relatados PF EM NÚMEROS', 'vDurMedIplRela');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos indiciamentos relativos:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos indiciamentos com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('Indiciamentos', 'vIndiciam');

// Título da medida mestra dos indiciamentos:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('Indiciamentos', 'Indiciamentos', 'Indiciamentos por Efetivo', 'Indiciamentos PF EM NÚMEROS', 'vIndiciam');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos re de recuperação de ativos instaurados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos re de recuperação de ativos instaurados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('ReRecAtivInstaurados', 'vReRecAtivInst');

// Título da medida mestra dos re de recuperação de ativos instaurados:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('ReRecAtivInstaurados', 'RE de Recuperação de Ativos Instaurados', 'RE de Recuperação de Ativos Instaurados por Efetivo', 'RE de Recuperação de Ativos Instaurados PF EM NÚMEROS', 'vReRecAtivInst');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos re de recuperação de ativos relatados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos re de recuperação de ativos relatados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('ReRecAtivRelatados', 'vReRecAtivRelat');

// Título da medida mestra dos re de recuperação de ativos relatados:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('ReRecAtivRelatados', 'RE de Recuperação de Ativos Relatados', 'RE de Recuperação de Ativos Relatados por Efetivo', 'RE de Recuperação de Ativos Relatados PF EM NÚMEROS', 'vReRecAtivRelat');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos RE de recuperação de ativos em andamento 
//-----------------------------------------------------------------------------------------------

// Medida mestra dos RE de recuperação de ativos em andamento com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolSemRel4('ReRecAtivEmAndamento', 'vReRecAtivEmAnd');

// Título da medida mestra dos RE de recuperação de ativos em andamento:

// Títulos gerados por SUB (etapa 2):
CALL GerarTitulosEpolSemRelAnoAtual3('ReRecAtivEmAndamento', 'RE de Recuperação de Ativos Em Andamento', 'RE de Recuperação de Ativos Em Andamento por Efetivo', 'RE de Recuperação de Ativos Em Andamento PF EM NÚMEROS');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras da duração média dos RE de recuperação de ativos em andamento 
//-----------------------------------------------------------------------------------------------

// Medida mestra da duração média dos RE de recuperação de ativos em andamento com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasDuracaoEpolSemRel2('DuracaoMediaReRecAtivEmAndamento', 'vDurMedReRecAtivEmAnd');

// Título da medida mestra da duração média dos RE de recuperação de ativos em andamento:

// Títulos gerados por SUB (etapa 2):
CALL GerarTitulosEpolDuracaoSemRelAnoAtual('DuracaoMediaReRecAtivEmAndamento', 'Duração Média dos Inquéritos Em Andamento', 'Duração Média dos Inquéritos Em Andamento em '' & ''@(=Year(Today()))');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos percentuais de inquéritos relatados por instaurados.
//-----------------------------------------------------------------------------------------------

// Medida mestra dos percentuais de inquéritos relatados por instaurados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('InqueritosRelatadosPorInstaurados', 'vIplRelatPorInst');

// Título da medida mestra dos percentuais de inquéritos relatados por instaurados:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2SemEfet('InqueritosRelatadosPorInstaurados', 'Inquéritos Relatados por Instaurados', 'Inquéritos Relatados por Instaurados PF EM NÚMEROS', 'vIplRelatPorInst');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos solucionados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos solucionados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosSolucionados', 'vIplSoluc');

// Título da medida mestra dos inquéritos solucionados:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('InqueritosSolucionados', 'Inquéritos Solucionados', 'Inquéritos Solucionados por Efetivo', 'Inquéritos Solucionados PF EM NÚMEROS', 'vIplSoluc');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos percentuais de inquéritos solucionados.
//-----------------------------------------------------------------------------------------------

// Medida mestra dos percentuais de inquéritos solucionados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('PercentualInqueritosSolucionados', 'vPercIplSoluc');

// Título da medida mestra dos percentuais de inquéritos solucionados:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2SemEfet('PercentualInqueritosSolucionados', '% de Inquéritos Solucionados', '% de Inquéritos Solucionados PF EM NÚMEROS', 'vPercIplSoluc');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos com autoria identificada relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos com autoria identificada com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosComAutoriaIdentificada', 'vIplComAutIdent');

// Título da medida mestra dos inquéritos com autoria identificada:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('InqueritosComAutoriaIdentificada', 'Inquéritos Com Autoria Identificada', 'Inquéritos Com Autoria Identificada por Efetivo', 'Inquéritos Com Autoria Identificada PF EM NÚMEROS', 'vIplComAutIdent');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos percentuais de inquéritos com autoria identificada.
//-----------------------------------------------------------------------------------------------

// Medida mestra dos percentuais de inquéritos com autoria identificada com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('PercentualInqueritosComAutoriaIdentificada', 'vPercIplComAutIdent');

// Título da medida mestra dos percentuais de inquéritos com autoria identificada:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2SemEfet('PercentualInqueritosComAutoriaIdentificada', '% de Inquéritos com Autoria Identificada', '% de Inquéritos com Autoria Identificada PF EM NÚMEROS', 'vPercIplComAutIdent');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos não crime relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos não crime com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosNaoCrime', 'vIplNaoCrime');

// Título da medida mestra dos inquéritos não crime:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('InqueritosNaoCrime', 'Inquéritos Não Crime', 'Inquéritos Não Crime por Efetivo', 'Inquéritos Não Crime PF EM NÚMEROS', 'vIplNaoCrime');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos percentuais de inquéritos não crime.
//-----------------------------------------------------------------------------------------------

// Medida mestra dos percentuais de inquéritos não crime com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('PercentualInqueritosNaoCrimes', 'vPercIplNaoCrime');

// Título da medida mestra dos percentuais de inquéritos não crime:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2SemEfet('PercentualInqueritosNaoCrimes', '% de Inquéritos Não Crime', '% de Inquéritos Não Crime PF EM NÚMEROS', 'vPercIplNaoCrime');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos inquéritos não solucionados relativas:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos inquéritos não solucionados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('InqueritosNaoSolucionados', 'vIplNaoSoluc');

// Título da medida mestra dos inquéritos não solucionados:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('InqueritosNaoSolucionados', 'Inquéritos Não Solucionados', 'Inquéritos Não Solucionados por Efetivo', 'Inquéritos Não Solucionados PF EM NÚMEROS', 'vIplNaoSoluc');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos percentuais de inquéritos não solucionados.
//-----------------------------------------------------------------------------------------------

// Medida mestra dos percentuais de inquéritos não solucionados com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('PercentualInqueritosNaoSolucionados', 'vPercIplNaoSoluc');

// Título da medida mestra dos percentuais de inquéritos não solucionados:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2SemEfet('PercentualInqueritosNaoSolucionados', '% de Inquéritos Não Solucionados', '% de Inquéritos Não Solucionados PF EM NÚMEROS', 'vPercIplNaoSoluc');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos percentuais de inquéritos instaurados por iniciativa própria.
//-----------------------------------------------------------------------------------------------

// Medida mestra dos percentuais de inquéritos instaurados por iniciativa própria com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData2('InqueritosInstauradosPorIniciativaPropriaPorInstaurados', 'vIplInstInicPropPorInst');

// Título da medida mestra dos percentuais de inquéritos instaurados por iniciativa própria:

// Títulos e rodapé gerados por SUB (etapa 2):
CALL GerarTitulosERodapeEpolProcData2SemEfet('InqueritosInstauradosPorIniciativaPropriaPorInstaurados', 'Percentual dos Inquéritos Instaurados por Iniciativa Própria', 'Percentual dos Inquéritos Instaurados por Iniciativa Própria PF EM NÚMEROS', 'vIplInstInicPropPorInst');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos indiciamentos SÓ PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra para KPI dos indiciamentos SÓ PF EM NÚMEROS com seleção de Ano, Mês ou Data, para mostrar dados do ano atual quando nada estiver selecionado:
// Medida SoPf gerada por SUB (etapa 1):
CALL GerarMedidaSoPfKpiEpolProcData('Indiciamentos', 'vIndiciam');

// Título da medida mestra para KPI dos indiciamentos SÓ PF EM NÚMEROS:
// Títulos SoPf gerados por SUB (etapa 2):
CALL GerarTitulosSoPfKpiEpolProcData('Indiciamentos', 'Indiciamentos');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos indiciamentos em áreas de fronteira relativos:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra dos indiciamentos em áreas de fronteira com seleção de Ano, Mês ou Data:
// Medidas geradas por SUB (etapa 1):
CALL GerarMedidasMestrasEpolProcData6('IndiciamentosEmAreasFronteira', 'vIndiciamEmAreaFront');

// Título da medida mestra dos indiciamentos em áreas de fronteira:

// Títulos e rodapé gerados por SUB (etapa 1):
CALL GerarTitulosERodapeEpolProcData('IndiciamentosEmAreasFronteira', 'Indiciamentos em Áreas de Fronteira', 'Indiciamentos em Áreas de Fronteira por Efetivo', 'Indiciamentos em Áreas de Fronteira PF EM NÚMEROS', 'vIndiciamEmAreaFront');

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras dos indiciamentos em áreas de fronteira SÓ PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

// Medida mestra para KPI dos indiciamentos em áreas de fronteira SÓ PF EM NÚMEROS com seleção de Ano, Mês ou Data, para mostrar dados do ano atual quando nada estiver selecionado:
// Medida SoPf gerada por SUB (etapa 1):
CALL GerarMedidaSoPfKpiEpolProcData('IndiciamentosEmAreasFronteira', 'vIndiciamEmAreaFront');

// Título da medida mestra para KPI dos indiciamentos em áreas de fronteira SÓ PF EM NÚMEROS:
// Títulos SoPf gerados por SUB (etapa 2):
CALL GerarTitulosSoPfKpiEpolProcData('IndiciamentosEmAreasFronteira', 'Indiciamentos em Áreas de Fronteira');
