TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Iniciando carga das Medidas Mestras de Efetivo;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

// Variáveis de medidas mestras em cada tela do APP

/*******************************************************************************
    OBS: 
    - as variáveis de medida mestra que terminam sem 'Tot' deve ser usadas
    nos gráficos que usam dimensões de Unidade ou localizações etc.
    - as variáveis de medida mestra que terminam com 'Tot' deve ser usadas
    nos gráficos que usam dimensões de Data Mês Ano etc. DATA=*TOT
*******************************************************************************/

//-----------------------------------------------------------------------------------------------
// Medidas Mestras de Efetivo
//-----------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos com Sede:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos com Sede:
SET vMedidaMestraQtdServPFComSede =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFComSede),
        // números efetivo PF
            $(vQtdServPFComSede),
        // números PF EM NÚMEROS
            $(vQtdServPFComSede)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFComSede);

// Medida mestra efetivos com Sede soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFComSedeSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFComSedeSomAnter),
        // números efetivo PF
            $(vQtdServPFComSedeSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFComSedeSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFComSedeSomAnter);

// Título da medida mestra efetivos com Sede:
SET vTituloMedidaMestraQtdServPFComSede = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PF Com Sede',
        'Efetivo PF Com Sede',
        'Efetivo PF Com Sede'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPFComSede);

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem Sede:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem Sede:
SET vMedidaMestraQtdServPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPF),
        // números efetivo PF
            $(vQtdServPF),
        // números PF EM NÚMEROS
            $(vQtdServPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPF);

// Medida mestra efetivos sem Sede soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFSomAnter),
        // números efetivo PF
            $(vQtdServPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFSomAnter);

// Título da medida mestra efetivos sem Sede:
SET vTituloMedidaMestraQtdServPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PF Sem Sede',
        'Efetivo PF Sem Sede',
        'Efetivo PF Sem Sede'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos na Sede:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos na Sede:
SET vMedidaMestraQtdServPFSede =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFSede),
        // números efetivo PF
            $(vQtdServPFSede),
        // números PF EM NÚMEROS
            $(vQtdServPFSede)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFSede);

// Medida mestra efetivos na Sede soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFSedeSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFSedeSomAnter),
        // números efetivo PF
            $(vQtdServPFSedeSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFSedeSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFSedeSomAnter);

// Título da medida mestra efetivos na Sede:
SET vTituloMedidaMestraQtdServPFSede = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Sede',
        'Efetivo Sede',
        'Efetivo Sede'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPFSede);



//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos nas SR:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos nas SR:
SET vMedidaMestraQtdServPFSR =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFSR),
        // números efetivo PF
            $(vQtdServPFSR),
        // números PF EM NÚMEROS
            $(vQtdServPFSR)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFSR);

// Medida mestra efetivos nas SR soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFSRSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFSRSomAnter),
        // números efetivo PF
            $(vQtdServPFSRSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFSRSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFSRSomAnter);

// Título da medida mestra efetivos nas SR:
SET vTituloMedidaMestraQtdServPFSR = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo SR',
        'Efetivo SR',
        'Efetivo SR'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPFSR);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos nas Descentralizadas:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos nas Descentralizadas:
SET vMedidaMestraQtdServPFDescentralizadas =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFDescentralizadas),
        // números efetivo PF
            $(vQtdServPFDescentralizadas),
        // números PF EM NÚMEROS
            $(vQtdServPFDescentralizadas)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFDescentralizadas);

// Medida mestra efetivos nas Descentralizadas soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFDescentralizadasSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFDescentralizadasSomAnter),
        // números efetivo PF
            $(vQtdServPFDescentralizadasSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFDescentralizadasSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFDescentralizadasSomAnter);

// Título da medida mestra efetivos nas Descentralizadas:
SET vTituloMedidaMestraQtdServPFDescentralizadas = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Descentralizadas',
        'Efetivo Descentralizadas',
        'Efetivo Descentralizadas'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPFDescentralizadas);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos nas Bases:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos nas Bases:
SET vMedidaMestraQtdServPFBases =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFBases),
        // números efetivo PF
            $(vQtdServPFBases),
        // números PF EM NÚMEROS
            $(vQtdServPFBases)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFBases);

// Medida mestra efetivos nas Bases soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFBasesSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFBasesSomAnter),
        // números efetivo PF
            $(vQtdServPFBasesSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFBasesSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFBasesSomAnter);

// Título da medida mestra efetivos nas Bases:
SET vTituloMedidaMestraQtdServPFBases = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Bases',
        'Efetivo Bases',
        'Efetivo Bases'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPFBases);




//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos nas Delegacias Especializadas PJ:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos nas Delegacias Especializadas PJ:
SET vMedidaMestraQtdServPFDelegaciasEspecializadasPJ =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFDelegaciasEspecializadasPJ),
        // números efetivo PF
            $(vQtdServPFDelegaciasEspecializadasPJ),
        // números PF EM NÚMEROS
            $(vQtdServPFDelegaciasEspecializadasPJ)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFDelegaciasEspecializadasPJ);

// Medida mestra efetivos nas Delegacias Especializadas PJ soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPFDelegaciasEspecializadasPJSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPFDelegaciasEspecializadasPJSomAnter),
        // números efetivo PF
            $(vQtdServPFDelegaciasEspecializadasPJSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPFDelegaciasEspecializadasPJSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPFDelegaciasEspecializadasPJSomAnter);

// Título da medida mestra efetivos nas Delegacias Especializadas PJ:
SET vTituloMedidaMestraQtdServPFDelegaciasEspecializadasPJ = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Delegacias Especializadas PJ',
        'Efetivo Delegacias Especializadas PJ',
        'Efetivo Delegacias Especializadas PJ'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPFDelegaciasEspecializadasPJ);





//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos DPF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos DPF:
SET vMedidaMestraQtdServDPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServDPF),
        // números efetivo PF
            $(vQtdServDPF),
        // números PF EM NÚMEROS
            $(vQtdServDPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServDPF);

// Medida mestra efetivos DPF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServDPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServDPFSomAnter),
        // números efetivo PF
            $(vQtdServDPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServDPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServDPFSomAnter);

// Título da medida mestra efetivos DPF:
SET vTituloMedidaMestraQtdServDPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo DPF',
        'Efetivo DPF',
        'Efetivo DPF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServDPF);




//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos APF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos APF:
SET vMedidaMestraQtdServAPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServAPF),
        // números efetivo PF
            $(vQtdServAPF),
        // números PF EM NÚMEROS
            $(vQtdServAPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServAPF);

// Medida mestra efetivos APF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServAPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServAPFSomAnter),
        // números efetivo PF
            $(vQtdServAPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServAPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServAPFSomAnter);

// Título da medida mestra efetivos APF:
SET vTituloMedidaMestraQtdServAPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo APF',
        'Efetivo APF',
        'Efetivo APF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServAPF);



//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos EPF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos EPF:
SET vMedidaMestraQtdServEPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServEPF),
        // números efetivo PF
            $(vQtdServEPF),
        // números PF EM NÚMEROS
            $(vQtdServEPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServEPF);

// Medida mestra efetivos EPF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServEPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServEPFSomAnter),
        // números efetivo PF
            $(vQtdServEPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServEPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServEPFSomAnter);

// Título da medida mestra efetivos EPF:
SET vTituloMedidaMestraQtdServEPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo EPF',
        'Efetivo EPF',
        'Efetivo EPF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServEPF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos PPF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos PPF:
SET vMedidaMestraQtdServPPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPPF),
        // números efetivo PF
            $(vQtdServPPF),
        // números PF EM NÚMEROS
            $(vQtdServPPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPPF);

// Medida mestra efetivos PPF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPPFSomAnter),
        // números efetivo PF
            $(vQtdServPPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPPFSomAnter);

// Título da medida mestra efetivos PPF:
SET vTituloMedidaMestraQtdServPPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PPF',
        'Efetivo PPF',
        'Efetivo PPF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPPF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos PCF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos PCF:
SET vMedidaMestraQtdServPCF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPCF),
        // números efetivo PF
            $(vQtdServPCF),
        // números PF EM NÚMEROS
            $(vQtdServPCF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPCF);

// Medida mestra efetivos PCF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServPCFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServPCFSomAnter),
        // números efetivo PF
            $(vQtdServPCFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServPCFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServPCFSomAnter);

// Título da medida mestra efetivos PCF:
SET vTituloMedidaMestraQtdServPCF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PCF',
        'Efetivo PCF',
        'Efetivo PCF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServPCF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos ADM:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos ADM:
SET vMedidaMestraQtdServADM =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServADM),
        // números efetivo PF
            $(vQtdServADM),
        // números PF EM NÚMEROS
            $(vQtdServADM)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServADM);

// Medida mestra efetivos ADM soma acumulada (soma anteriores):
SET vMedidaMestraQtdServADMSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServADMSomAnter),
        // números efetivo PF
            $(vQtdServADMSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServADMSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServADMSomAnter);

// Título da medida mestra efetivos ADM:
SET vTituloMedidaMestraQtdServADM = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo ADM',
        'Efetivo ADM',
        'Efetivo ADM'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServADM);

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas com Sede:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas com Sede:
SET vMedidaMestraQtdServSemRelDatasPFComSede =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFComSede),
        // números efetivo PF
            $(vQtdServSemRelDatasPFComSede),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFComSede)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFComSede);

// Medida mestra efetivos sem relacionar às datas com Sede soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFComSedeSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFComSedeSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFComSedeSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFComSedeSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFComSedeSomAnter);

// Título da medida mestra efetivos sem relacionar às datas com Sede:
SET vTituloMedidaMestraQtdServSemRelDatasPFComSede = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PF Com Sede',
        'Efetivo PF Com Sede',
        'Efetivo PF Com Sede'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPFComSede);

//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas sem Sede:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas sem Sede:
SET vMedidaMestraQtdServSemRelDatasPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPF),
        // números efetivo PF
            $(vQtdServSemRelDatasPF),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPF);

// Medida mestra efetivos sem relacionar às datas sem Sede soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFSomAnter);

// Título da medida mestra efetivos sem relacionar às datas sem Sede:
SET vTituloMedidaMestraQtdServSemRelDatasPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PF Sem Sede',
        'Efetivo PF Sem Sede',
        'Efetivo PF Sem Sede'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas na Sede:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas na Sede:
SET vMedidaMestraQtdServSemRelDatasPFSede =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFSede),
        // números efetivo PF
            $(vQtdServSemRelDatasPFSede),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFSede)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFSede);

// Medida mestra efetivos sem relacionar às datas na Sede soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFSedeSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFSedeSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFSedeSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFSedeSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFSedeSomAnter);

// Título da medida mestra efetivos sem relacionar às datas na Sede:
SET vTituloMedidaMestraQtdServSemRelDatasPFSede = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Sede',
        'Efetivo Sede',
        'Efetivo Sede'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPFSede);



//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas nas SR:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas nas SR:
SET vMedidaMestraQtdServSemRelDatasPFSR =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFSR),
        // números efetivo PF
            $(vQtdServSemRelDatasPFSR),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFSR)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFSR);

// Medida mestra efetivos sem relacionar às datas nas SR soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFSRSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFSRSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFSRSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFSRSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFSRSomAnter);

// Título da medida mestra efetivos sem relacionar às datas nas SR:
SET vTituloMedidaMestraQtdServSemRelDatasPFSR = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo SR',
        'Efetivo SR',
        'Efetivo SR'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPFSR);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas nas Descentralizadas:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas nas Descentralizadas:
SET vMedidaMestraQtdServSemRelDatasPFDescentralizadas =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFDescentralizadas),
        // números efetivo PF
            $(vQtdServSemRelDatasPFDescentralizadas),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFDescentralizadas)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFDescentralizadas);

// Medida mestra efetivos sem relacionar às datas nas Descentralizadas soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFDescentralizadasSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFDescentralizadasSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFDescentralizadasSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFDescentralizadasSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFDescentralizadasSomAnter);

// Título da medida mestra efetivos sem relacionar às datas nas Descentralizadas:
SET vTituloMedidaMestraQtdServSemRelDatasPFDescentralizadas = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Descentralizadas',
        'Efetivo Descentralizadas',
        'Efetivo Descentralizadas'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPFDescentralizadas);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas nas Bases:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas nas Bases:
SET vMedidaMestraQtdServSemRelDatasPFBases =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFBases),
        // números efetivo PF
            $(vQtdServSemRelDatasPFBases),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFBases)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFBases);

// Medida mestra efetivos sem relacionar às datas nas Bases soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFBasesSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFBasesSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFBasesSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFBasesSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFBasesSomAnter);

// Título da medida mestra efetivos sem relacionar às datas nas Bases:
SET vTituloMedidaMestraQtdServSemRelDatasPFBases = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Bases',
        'Efetivo Bases',
        'Efetivo Bases'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPFBases);




//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas nas Delegacias Especializadas PJ:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas nas Delegacias Especializadas PJ:
SET vMedidaMestraQtdServSemRelDatasPFDelegaciasEspecializadasPJ =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFDelegaciasEspecializadasPJ),
        // números efetivo PF
            $(vQtdServSemRelDatasPFDelegaciasEspecializadasPJ),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFDelegaciasEspecializadasPJ)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFDelegaciasEspecializadasPJ);

// Medida mestra efetivos sem relacionar às datas nas Delegacias Especializadas PJ soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPFDelegaciasEspecializadasPJSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPFDelegaciasEspecializadasPJSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPFDelegaciasEspecializadasPJSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPFDelegaciasEspecializadasPJSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPFDelegaciasEspecializadasPJSomAnter);

// Título da medida mestra efetivos sem relacionar às datas nas Delegacias Especializadas PJ:
SET vTituloMedidaMestraQtdServSemRelDatasPFDelegaciasEspecializadasPJ = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo Delegacias Especializadas PJ',
        'Efetivo Delegacias Especializadas PJ',
        'Efetivo Delegacias Especializadas PJ'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPFDelegaciasEspecializadasPJ);





//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas DPF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas DPF:
SET vMedidaMestraQtdServSemRelDatasDPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasDPF),
        // números efetivo PF
            $(vQtdServSemRelDatasDPF),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasDPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasDPF);

// Medida mestra efetivos sem relacionar às datas DPF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasDPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasDPFSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasDPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasDPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasDPFSomAnter);

// Título da medida mestra efetivos sem relacionar às datas DPF:
SET vTituloMedidaMestraQtdServSemRelDatasDPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo DPF',
        'Efetivo DPF',
        'Efetivo DPF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasDPF);




//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas APF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas APF:
SET vMedidaMestraQtdServSemRelDatasAPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasAPF),
        // números efetivo PF
            $(vQtdServSemRelDatasAPF),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasAPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasAPF);

// Medida mestra efetivos sem relacionar às datas APF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasAPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasAPFSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasAPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasAPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasAPFSomAnter);

// Título da medida mestra efetivos sem relacionar às datas APF:
SET vTituloMedidaMestraQtdServSemRelDatasAPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo APF',
        'Efetivo APF',
        'Efetivo APF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasAPF);



//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas EPF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas EPF:
SET vMedidaMestraQtdServSemRelDatasEPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasEPF),
        // números efetivo PF
            $(vQtdServSemRelDatasEPF),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasEPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasEPF);

// Medida mestra efetivos sem relacionar às datas EPF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasEPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasEPFSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasEPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasEPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasEPFSomAnter);

// Título da medida mestra efetivos sem relacionar às datas EPF:
SET vTituloMedidaMestraQtdServSemRelDatasEPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo EPF',
        'Efetivo EPF',
        'Efetivo EPF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasEPF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas PPF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas PPF:
SET vMedidaMestraQtdServSemRelDatasPPF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPPF),
        // números efetivo PF
            $(vQtdServSemRelDatasPPF),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPPF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPPF);

// Medida mestra efetivos sem relacionar às datas PPF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPPFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPPFSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPPFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPPFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPPFSomAnter);

// Título da medida mestra efetivos sem relacionar às datas PPF:
SET vTituloMedidaMestraQtdServSemRelDatasPPF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PPF',
        'Efetivo PPF',
        'Efetivo PPF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPPF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas PCF:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas PCF:
SET vMedidaMestraQtdServSemRelDatasPCF =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPCF),
        // números efetivo PF
            $(vQtdServSemRelDatasPCF),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPCF)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPCF);

// Medida mestra efetivos sem relacionar às datas PCF soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasPCFSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasPCFSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasPCFSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasPCFSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasPCFSomAnter);

// Título da medida mestra efetivos sem relacionar às datas PCF:
SET vTituloMedidaMestraQtdServSemRelDatasPCF = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo PCF',
        'Efetivo PCF',
        'Efetivo PCF'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasPCF);


//-----------------------------------------------------------------------------------------------
// Cálculo das medidas mestras efetivos sem relacionar às datas ADM:
//      - numeros absolutos
//      - números efetivo PF
//      - números PF EM NÚMEROS (dummy)
//-----------------------------------------------------------------------------------------------

// Medida mestra efetivos sem relacionar às datas ADM:
SET vMedidaMestraQtdServSemRelDatasADM =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasADM),
        // números efetivo PF
            $(vQtdServSemRelDatasADM),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasADM)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasADM);

// Medida mestra efetivos sem relacionar às datas ADM soma acumulada (soma anteriores):
SET vMedidaMestraQtdServSemRelDatasADMSomAnter =
        PICK(
            @(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        // numeros absolutos 
            $(vQtdServSemRelDatasADMSomAnter),
        // números efetivo PF
            $(vQtdServSemRelDatasADMSomAnter),
        // números PF EM NÚMEROS
            $(vQtdServSemRelDatasADMSomAnter)
            )
;

Call TratarExpansaoMacro(vMedidaMestraQtdServSemRelDatasADMSomAnter);

// Título da medida mestra efetivos sem relacionar às datas ADM:
SET vTituloMedidaMestraQtdServSemRelDatasADM = 
    PICK(@(vMostrarValAbsouRelaoEfetouPFEmNum)+1,
        'Efetivo ADM',
        'Efetivo ADM',
        'Efetivo ADM'
        )
;

Call TratarExpansaoMacro(vTituloMedidaMestraQtdServSemRelDatasADM);
