// End time and duration
LET vReloadEnd   = Now();
LET vReloadDur   = Interval(vReloadEnd - vReloadStart, 'hh:mm:ss');

// Store in a one-row table for visuals
ReloadLog:
LOAD
    '$(vReloadStart)' AS ReloadStart,
    '$(vReloadEnd)'   AS ReloadEnd,
    '$(vReloadDur)'   AS ReloadDuration
AUTOGENERATE 1;


TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga de transformação de dados;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;