TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_TNBIA;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

/*
    Autor: Eduardo Moreno Izel
    Data: 2026-04-21
    Descrição: Carrega a tabela a Taxonomia Nacional de Bens de Interesse 
    à Apreensão - TNBIA, extraída diretamente dos itens de apreensão constantes
    no DIM_CASOS_APREENSAO_BENS.qvd
*/

TEMP_TNBIA:
LOAD distinct
    "GestãoBens Item Material Subclasse Código",
    "GestãoBens Item Material ID",
    "GestãoBens Item Material",
    "GestãoBens Item Material Classe",
    "GestãoBens Item Material Categoria",
    Now() as DataHoraCarga
// FROM [lib://MD_EPOL/DIM_CASOS_APREENSAO_BENS.qvd]
FROM [$(vCarregaDIM_CASOS_APREENSAO_BENS)]
(qvd)
;

// Tabela TNBIA_DIM_CASOS_APREENSAO_BENS para gravação em formato .csv para
// auditoria dos itens da Taxonomia Nacional de Bens de Interesse à Apreensão
// - TNBIA, atualmente em uso na DIM_CASOS_APREENSAO_BENS.qvd


NoConcatenate
TNBIA_DIM_CASOS_APREENSAO_BENS:
Load
	*
RESIDENT TEMP_TNBIA;

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Gravando TNBIA_DIM_CASOS_APREENSAO_BENS.csv;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

TRACE >>> Gravando CSV TNBIA;
CALL StoreAndDropCsv('TNBIA_DIM_CASOS_APREENSAO_BENS', '$(vCaminhoTabelasCorpDicorNge)'); //

// NoConcatenate
// [TEMP_TNBIA_01_04_2026]:
// LOAD distinct
//     "GestãoBens Item Material Subclasse Código",
//     "GestãoBens Item Material ID",
//     "GestãoBens Item Material",
//     "GestãoBens Item Material Classe",
//     "GestãoBens Item Material Categoria"
// FROM [lib://MD_EPOL/DIM_CASOS_APREENSAO_BENS.qvd]
// (qvd)
// ;
// CALL StoreCsv('TEMP_TNBIA_01_04_2026', '$(vCaminhoTabelasTeste)'); //
// CALL StoreAndDrop('TEMP_TNBIA_01_04_2026', '$(vCaminhoTabelasTeste)'); //

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída Carga TEMP_TNBIA;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;