TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Iniciando carga das variáveis das Métricas de Apreensões;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

//-----------------------------------------------------------------------------------------------
// Variáveis de métricas de apreensões - versão parametrizada
//-----------------------------------------------------------------------------------------------
// Observações:
//      SomaAnteriores já é o Pareto
//      DtMesAno quando o cálculo inclui o "Tipo do Fato"
//      DtMesAnoApre quando o cálculo não inclui o "Tipo do Fato"
//-----------------------------------------------------------------------------------------------

//==============================================================================================
// SUBROUTINES AUXILIARES
//==============================================================================================

SUB GerarConjunto12Apre(vNomeFiltro)
    SET vListaConjunto =
                $($(vNomeFiltro))
                ,[Tipo da Data] = {'Apreensão'}|
                $($(vNomeFiltro))
                ,[Tipo da Data] = {'Apreensão'}
                ,$(vConjApreDtMesAnoPfEmNumeros)|
                $($(vNomeFiltro))|
                $($(vNomeFiltro))
                ,$(vConjApreDtMesAnoAprePfEmNumeros)|
                [Ano] = {@(=Year(Today()))}
                ,$($(vNomeFiltro))
                ,[Tipo da Data] = {'Apreensão'}|
                [Ano] = {@(=Year(Today()))}
                ,$($(vNomeFiltro))
                ,[Tipo da Data] = {'Apreensão'}
                ,$(vConjApreDtMesAnoPfEmNumeros)|
                $($(vNomeFiltro))
                ,[Ano da Apreensão] = {@(=Year(Today()))}|
                $($(vNomeFiltro))
                ,[Ano da Apreensão] = {@(=Year(Today()))}
                ,$(vConjApreDtMesAnoAprePfEmNumeros)|
                [Ano] = {@(=MAX([Ano]-1))}
                ,$($(vNomeFiltro))
                ,[Tipo da Data] = {'Apreensão'}|
                [Ano] = {@(=MAX([Ano]-1))}
                ,$($(vNomeFiltro))
                ,[Tipo da Data] = {'Apreensão'}
                ,$(vConjApreDtMesAnoPfEmNumeros)|
                $($(vNomeFiltro))
                ,[Ano da Apreensão] = {@(=MAX([Ano da Apreensão]-1))}|
                $($(vNomeFiltro))
                ,[Ano da Apreensão] = {@(=MAX([Ano da Apreensão]-1))}
                ,$(vConjApreDtMesAnoAprePfEmNumeros)
                ;
END SUB

SUB GerarListaNomes12Apre(vRadical)
    SET vListaNomeVariavel =
$(vRadical)DtMesAno|
$(vRadical)PfEmNumDtMesAno|
$(vRadical)DtMesAnoApre|
$(vRadical)PfEmNumDtMesAnoApre|
$(vRadical)AnoAtual|
$(vRadical)PfEmNumAnoAtual|
$(vRadical)AnoApreAtual|
$(vRadical)PfEmNumAnoApreAtual|
$(vRadical)AnoAnterior|
$(vRadical)PfEmNumAnoAnterior|
$(vRadical)AnoApreAnterior|
$(vRadical)PfEmNumAnoApreAnterior
;
END SUB

SUB GerarListaNomesSomAnter12Apre(vRadical)
    SET vListaNomeVariavel =
$(vRadical)SomAnterDtMesAno|
$(vRadical)SomAnterPfEmNumDtMesAno|
$(vRadical)SomAnterDtMesAnoApre|
$(vRadical)SomAnterPfEmNumDtMesAnoApre|
$(vRadical)SomAnterAnoAtual|
$(vRadical)SomAnterPfEmNumAnoAtual|
$(vRadical)SomAnterAnoApreAtual|
$(vRadical)SomAnterPfEmNumAnoApreAtual|
$(vRadical)SomAnterAnoAnterior|
$(vRadical)SomAnterPfEmNumAnoAnterior|
$(vRadical)SomAnterAnoApreAnterior|
$(vRadical)SomAnterPfEmNumAnoApreAnterior
;
END SUB

SUB GerarListaCampo12(vCampo)
    SET vListaCampo =
$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)|$(vCampo)
;
END SUB

SUB GerarPorEfet6Reais(vRadical)
    SET vListaNomeVariavel =
$(vRadical)DtMesAnoPorEfet|
$(vRadical)DtMesAnoAprePorEfet|
$(vRadical)AnoAtualPorEfet|
$(vRadical)AnoApreAtualPorEfet|
$(vRadical)AnoAnteriorPorEfet|
$(vRadical)AnoApreAnteriorPorEfet
;
    SET vListaNumerador =
$($(vRadical)DtMesAno)|
$($(vRadical)DtMesAnoApre)|
$($(vRadical)AnoAtual)|
$($(vRadical)AnoApreAtual)|
$($(vRadical)AnoAnterior)|
$($(vRadical)AnoApreAnterior)
;
    SET vListaDenominador =
$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)
;
    FOR i = 1 TO 6
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaReais('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i

    SET vListaNomeVariavel =
$(vRadical)DtMesAnoPorEfetTot|
$(vRadical)DtMesAnoAprePorEfetTot|
$(vRadical)AnoAtualPorEfetTot|
$(vRadical)AnoApreAtualPorEfetTot|
$(vRadical)AnoAnteriorPorEfetTot|
$(vRadical)AnoApreAnteriorPorEfetTot
;
    SET vListaDenominador =
$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)
;
    FOR i = 1 TO 6
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaReais('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i
END SUB

SUB GerarPorEfet6Mi(vRadical)
    SET vListaNomeVariavel =
$(vRadical)DtMesAnoPorEfet|
$(vRadical)DtMesAnoAprePorEfet|
$(vRadical)AnoAtualPorEfet|
$(vRadical)AnoApreAtualPorEfet|
$(vRadical)AnoAnteriorPorEfet|
$(vRadical)AnoApreAnteriorPorEfet
;
    SET vListaNumerador =
$($(vRadical)DtMesAno)|
$($(vRadical)DtMesAnoApre)|
$($(vRadical)AnoAtual)|
$($(vRadical)AnoApreAtual)|
$($(vRadical)AnoAnterior)|
$($(vRadical)AnoApreAnterior)
;
    SET vListaDenominador =
$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)
;
    FOR i = 1 TO 6
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaMi('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i

    SET vListaNomeVariavel =
$(vRadical)DtMesAnoPorEfetTot|
$(vRadical)DtMesAnoAprePorEfetTot|
$(vRadical)AnoAtualPorEfetTot|
$(vRadical)AnoApreAtualPorEfetTot|
$(vRadical)AnoAnteriorPorEfetTot|
$(vRadical)AnoApreAnteriorPorEfetTot
;
    SET vListaDenominador =
$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)
;
    FOR i = 1 TO 6
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaMi('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i
END SUB

SUB GerarPorEfet6Bi(vRadical)
    SET vListaNomeVariavel =
$(vRadical)DtMesAnoPorEfet|
$(vRadical)DtMesAnoAprePorEfet|
$(vRadical)AnoAtualPorEfet|
$(vRadical)AnoApreAtualPorEfet|
$(vRadical)AnoAnteriorPorEfet|
$(vRadical)AnoApreAnteriorPorEfet
;
    SET vListaNumerador =
$($(vRadical)DtMesAno)|
$($(vRadical)DtMesAnoApre)|
$($(vRadical)AnoAtual)|
$($(vRadical)AnoApreAtual)|
$($(vRadical)AnoAnterior)|
$($(vRadical)AnoApreAnterior)
;
    SET vListaDenominador =
$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)|$(vServPJ)
;
    FOR i = 1 TO 6
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaBi('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i

    SET vListaNomeVariavel =
$(vRadical)DtMesAnoPorEfetTot|
$(vRadical)DtMesAnoAprePorEfetTot|
$(vRadical)AnoAtualPorEfetTot|
$(vRadical)AnoApreAtualPorEfetTot|
$(vRadical)AnoAnteriorPorEfetTot|
$(vRadical)AnoApreAnteriorPorEfetTot
;
    SET vListaDenominador =
$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)|$(vServPJTotal)
;
    FOR i = 1 TO 6
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaBi('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i
END SUB

SUB GerarMetricaReaisCompleta(vRadical, vNomeFiltro, vCampo)
    CALL GerarListaNomes12Apre('$(vRadical)');
    CALL GerarConjunto12Apre('$(vNomeFiltro)');
    CALL GerarListaCampo12('$(vCampo)');

    FOR i = 1 TO 12
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vConjunto = SubField('$(vListaConjunto)', '|', i);
        LET vCampoLocal = SubField('$(vListaCampo)', '|', i);
        CALL CriarVariavelSomaReais('$(vNomeVariavel)', '$(vConjunto)', '$(vCampoLocal)');
    NEXT i

    CALL GerarPorEfet6Reais('$(vRadical)');

    CALL GerarListaNomesSomAnter12Apre('$(vRadical)');
    CALL GerarConjunto12Apre('$(vNomeFiltro)');
    CALL GerarListaCampo12('$(vCampo)');

    FOR i = 1 TO 12
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vConjunto = SubField('$(vListaConjunto)', '|', i);
        LET vCampoLocal = SubField('$(vListaCampo)', '|', i);
        CALL CriarVariavelSomaReaisAnteriores('$(vNomeVariavel)', '$(vConjunto)', '$(vCampoLocal)');
    NEXT i
END SUB

SUB GerarMetricaMiCompleta(vRadical, vNomeFiltro, vCampo)
    CALL GerarListaNomes12Apre('$(vRadical)');
    CALL GerarConjunto12Apre('$(vNomeFiltro)');
    CALL GerarListaCampo12('$(vCampo)');

    FOR i = 1 TO 12
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vConjunto = SubField('$(vListaConjunto)', '|', i);
        LET vCampoLocal = SubField('$(vListaCampo)', '|', i);
        CALL CriarVariavelSomaMi('$(vNomeVariavel)', '$(vConjunto)', '$(vCampoLocal)');
    NEXT i

    CALL GerarPorEfet6Mi('$(vRadical)');
END SUB

SUB GerarMetricaBiCompleta(vRadical, vNomeFiltro, vCampo)
    CALL GerarListaNomes12Apre('$(vRadical)');
    CALL GerarConjunto12Apre('$(vNomeFiltro)');
    CALL GerarListaCampo12('$(vCampo)');

    FOR i = 1 TO 12
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vConjunto = SubField('$(vListaConjunto)', '|', i);
        LET vCampoLocal = SubField('$(vListaCampo)', '|', i);
        CALL CriarVariavelSomaBi('$(vNomeVariavel)', '$(vConjunto)', '$(vCampoLocal)');
    NEXT i

    CALL GerarPorEfet6Bi('$(vRadical)');
END SUB

SUB GerarProporcaoAprePercentual(vRadical, vNum, vDen)
    CALL GerarListaNomes12Apre('$(vRadical)');
    SET vListaNumerador =
$($(vNum)DtMesAno)|
$($(vNum)PfEmNumDtMesAno)|
$($(vNum)DtMesAnoApre)|
$($(vNum)PfEmNumDtMesAnoApre)|
$($(vNum)AnoAtual)|
$($(vNum)PfEmNumAnoAtual)|
$($(vNum)AnoApreAtual)|
$($(vNum)PfEmNumAnoApreAtual)|
$($(vNum)AnoAnterior)|
$($(vNum)PfEmNumAnoAnterior)|
$($(vNum)AnoApreAnterior)|
$($(vNum)PfEmNumAnoApreAnterior)
;
    SET vListaDenominador =
$($(vDen)DtMesAno)|
$($(vDen)PfEmNumDtMesAno)|
$($(vDen)DtMesAnoApre)|
$($(vDen)PfEmNumDtMesAnoApre)|
$($(vDen)AnoAtual)|
$($(vDen)PfEmNumAnoAtual)|
$($(vDen)AnoApreAtual)|
$($(vDen)PfEmNumAnoApreAtual)|
$($(vDen)AnoAnterior)|
$($(vDen)PfEmNumAnoAnterior)|
$($(vDen)AnoApreAnterior)|
$($(vDen)PfEmNumAnoApreAnterior)
;

    FOR i = 1 TO 12
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaPercentual('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i
END SUB

SUB GerarProporcaoMiPorOper(vRadical)
    CALL GerarListaNomes12Apre('$(vRadical)');
    SET vListaNumerador =
$(vValDescapMiDtMesAno)|
$(vValDescapMiPfEmNumDtMesAno)|
$(vValDescapMiDtMesAnoApre)|
$(vValDescapMiPfEmNumDtMesAnoApre)|
$(vValDescapMiAnoAtual)|
$(vValDescapMiPfEmNumAnoAtual)|
$(vValDescapMiAnoApreAtual)|
$(vValDescapMiPfEmNumAnoApreAtual)|
$(vValDescapMiAnoAnterior)|
$(vValDescapMiPfEmNumAnoAnterior)|
$(vValDescapMiAnoApreAnterior)|
$(vValDescapMiPfEmNumAnoApreAnterior)
;
    SET vListaDenominador =
$(vOperHomDtMesAno)|
$(vOperHomPfEmNumDtMesAno)|
$(vOperHomDtMesAnoDefl)|
$(vOperHomPfEmNumDtMesAnoDefl)|
$(vOperHomAnoAtual)|
$(vOperHomPfEmNumAnoAtual)|
$(vOperHomAnoDeflAtual)|
$(vOperHomPfEmNumAnoDeflAtual)|
$(vOperHomAnoAnterior)|
$(vOperHomPfEmNumAnoAnterior)|
$(vOperHomAnoDeflAnterior)|
$(vOperHomPfEmNumAnoDeflAnterior)
;

    FOR i = 1 TO 12
        LET vNomeVariavel = SubField('$(vListaNomeVariavel)', '|', i);
        LET vNumerador = SubField('$(vListaNumerador)', '|', i);
        LET vDenominador = SubField('$(vListaDenominador)', '|', i);
        CALL CriarVariavelRelativaMi('$(vNomeVariavel)', '$(vNumerador)', '$(vDenominador)');
    NEXT i
END SUB

//==============================================================================================
// FILTROS BASE
//==============================================================================================

SET vFApreBase   = [Tipo do Fato] = {'Apreensões'};
SET vFApreDesvio = [Área de Atribuição do Caso] = {'Desvio de Recursos Públicos'}, [Tipo do Fato] = {'Apreensões'};
SET vFApreFront  = AREA_FRONTEIRA = {"SIM"}, [Tipo do Fato] = {'Apreensões'};

//==============================================================================================
// MÉTRICAS BASE (REAIS)
//==============================================================================================

CALL GerarMetricaReaisCompleta('vValDescap',               'vFApreBase', '[Valor Total Descapitalização]');
CALL GerarMetricaReaisCompleta('vValImoveis',              'vFApreBase', '[1 Valor Bens Imóveis Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValMovSemov',             'vFApreBase', '[2 Valor Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValImovMov',              'vFApreBase', '[1+2 Bens Imóveis Apreendidos/Sequestrados + Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValCripto',               'vFApreBase', '[3 Valor Criptoativos apreendidos/sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValTilValMob',            'vFApreBase', '[4 Valor Títulos  Valores Mobiliários e Direitos Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValMonet',                'vFApreBase', '[5 Valores Monetários Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValMonTit',               'vFApreBase', '[4+5 Valores Monetários, Títulos e Direitos Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaReaisCompleta('vValPedMetJoiArte',        'vFApreBase', '[2.1 Valor Pedras, Metais Preciosos, Joias e Obras de Arte LVL2]');
CALL GerarMetricaReaisCompleta('vValSemov',                'vFApreBase', '[2.2 Valor Semoventes LVL2]');
CALL GerarMetricaReaisCompleta('vValVeicAer',              'vFApreBase', '[2.3 Valor Veículos aéreos LVL2]');
CALL GerarMetricaReaisCompleta('vValVeicAquat',            'vFApreBase', '[2.4 Valor Veículos aquáticos LVL2]');
CALL GerarMetricaReaisCompleta('vValVeicTerr',             'vFApreBase', '[2.5 Valor Veículos terrestres LVL2]');
CALL GerarMetricaReaisCompleta('vValOutMoveis',            'vFApreBase', '[2.6 Valor Outros bens Móvies LVL2]');
CALL GerarMetricaReaisCompleta('vValMonetEsp',             'vFApreBase', '[5.1 Valores Monetários em espécie LVL2]');
CALL GerarMetricaReaisCompleta('vValBacenjud',             'vFApreBase', '[5.2 Valores Monetários bloqueados via Bacenjud ou similares LVL2]');
CALL GerarMetricaReaisCompleta('vValSeqMovImovCriptBloq',  'vFApreBase', '[1+2+3+5.2 Sequestros e bloqueios (Sequestros Móveis e Imóveis + Criptoativos + Bloqueio Financeiro)]');
CALL GerarMetricaReaisCompleta('vItensDestr',              'vFApreBase', '[6 Valor Itens de Descapitalização Destruídos no Local LVL1]');

//==============================================================================================
// MÉTRICAS BASE (MILHÕES)
//==============================================================================================

CALL GerarMetricaMiCompleta('vValDescapMi',               'vFApreBase', '[Valor Total Descapitalização]');
CALL GerarMetricaMiCompleta('vValImoveisMi',              'vFApreBase', '[1 Valor Bens Imóveis Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValMovSemovMi',             'vFApreBase', '[2 Valor Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValImovMovMi',              'vFApreBase', '[1+2 Bens Imóveis Apreendidos/Sequestrados + Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValCriptoMi',               'vFApreBase', '[3 Valor Criptoativos apreendidos/sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValTilValMobMi',            'vFApreBase', '[4 Valor Títulos  Valores Mobiliários e Direitos Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValMonetMi',                'vFApreBase', '[5 Valores Monetários Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValMonTitMi',               'vFApreBase', '[4+5 Valores Monetários, Títulos e Direitos Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaMiCompleta('vValPedMetJoiArteMi',        'vFApreBase', '[2.1 Valor Pedras, Metais Preciosos, Joias e Obras de Arte LVL2]');
CALL GerarMetricaMiCompleta('vValSemovMi',                'vFApreBase', '[2.2 Valor Semoventes LVL2]');
CALL GerarMetricaMiCompleta('vValVeicAerMi',              'vFApreBase', '[2.3 Valor Veículos aéreos LVL2]');
CALL GerarMetricaMiCompleta('vValVeicAquatMi',            'vFApreBase', '[2.4 Valor Veículos aquáticos LVL2]');
CALL GerarMetricaMiCompleta('vValVeicTerrMi',             'vFApreBase', '[2.5 Valor Veículos terrestres LVL2]');
CALL GerarMetricaMiCompleta('vValOutMoveisMi',            'vFApreBase', '[2.6 Valor Outros bens Móvies LVL2]');
CALL GerarMetricaMiCompleta('vValMonetEspMi',             'vFApreBase', '[5.1 Valores Monetários em espécie LVL2]');
CALL GerarMetricaMiCompleta('vValBacenjudMi',             'vFApreBase', '[5.2 Valores Monetários bloqueados via Bacenjud ou similares LVL2]');
CALL GerarMetricaMiCompleta('vValSeqMovImovCriptBloqMi',  'vFApreBase', '[1+2+3+5.2 Sequestros e bloqueios (Sequestros Móveis e Imóveis + Criptoativos + Bloqueio Financeiro)]');
CALL GerarMetricaMiCompleta('vItensDestrMi',              'vFApreBase', '[6 Valor Itens de Descapitalização Destruídos no Local LVL1]');

//==============================================================================================
// MÉTRICAS BASE (BILHÕES)
//==============================================================================================

CALL GerarMetricaBiCompleta('vValDescapBi',               'vFApreBase', '[Valor Total Descapitalização]');
CALL GerarMetricaBiCompleta('vValImoveisBi',              'vFApreBase', '[1 Valor Bens Imóveis Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValMovSemovBi',             'vFApreBase', '[2 Valor Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValImovMovBi',              'vFApreBase', '[1+2 Bens Imóveis Apreendidos/Sequestrados + Bens Móveis e Semoventes Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValCriptoBi',               'vFApreBase', '[3 Valor Criptoativos apreendidos/sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValTilValMobBi',            'vFApreBase', '[4 Valor Títulos  Valores Mobiliários e Direitos Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValMonetBi',                'vFApreBase', '[5 Valores Monetários Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValMonTitBi',               'vFApreBase', '[4+5 Valores Monetários, Títulos e Direitos Apreendidos/Sequestrados LVL1]');
CALL GerarMetricaBiCompleta('vValPedMetJoiArteBi',        'vFApreBase', '[2.1 Valor Pedras, Metais Preciosos, Joias e Obras de Arte LVL2]');
CALL GerarMetricaBiCompleta('vValSemovBi',                'vFApreBase', '[2.2 Valor Semoventes LVL2]');
CALL GerarMetricaBiCompleta('vValVeicAerBi',              'vFApreBase', '[2.3 Valor Veículos aéreos LVL2]');
CALL GerarMetricaBiCompleta('vValVeicAquatBi',            'vFApreBase', '[2.4 Valor Veículos aquáticos LVL2]');
CALL GerarMetricaBiCompleta('vValVeicTerrBi',             'vFApreBase', '[2.5 Valor Veículos terrestres LVL2]');
CALL GerarMetricaBiCompleta('vValOutMoveisBi',            'vFApreBase', '[2.6 Valor Outros bens Móvies LVL2]');
CALL GerarMetricaBiCompleta('vValMonetEspBi',             'vFApreBase', '[5.1 Valores Monetários em espécie LVL2]');
CALL GerarMetricaBiCompleta('vValBacenjudBi',             'vFApreBase', '[5.2 Valores Monetários bloqueados via Bacenjud ou similares LVL2]');
CALL GerarMetricaBiCompleta('vValSeqMovImovCriptBloqBi',  'vFApreBase', '[1+2+3+5.2 Sequestros e bloqueios (Sequestros Móveis e Imóveis + Criptoativos + Bloqueio Financeiro)]');
CALL GerarMetricaBiCompleta('vItensDestrBi',              'vFApreBase', '[6 Valor Itens de Descapitalização Destruídos no Local LVL1]');

//==============================================================================================
// PROPORÇÕES
//==============================================================================================

// Nome solicitado pelo usuário
CALL GerarProporcaoMiPorOper('vValDescapMiPorOper');

// Nome legado para compatibilidade com front já existente
CALL GerarProporcaoMiPorOper('vValDescapMiPorOperHom');

CALL GerarProporcaoAprePercentual('vValDescapDesvioPorValDescap', 'vValDescapDesvio', 'vValDescap');

//==============================================================================================
// MÉTRICAS COM FILTRO
//==============================================================================================

CALL GerarMetricaReaisCompleta('vValDescapDesvio',      'vFApreDesvio', '[Valor Total Descapitalização]');
CALL GerarMetricaMiCompleta('vValDescapDesvioMi',       'vFApreDesvio', '[Valor Total Descapitalização]');

CALL GerarMetricaReaisCompleta('vValDescapEmAreaFront', 'vFApreFront',  '[Valor Total Descapitalização]');
CALL GerarMetricaMiCompleta('vValDescapEmAreaFrontMi',  'vFApreFront',  '[Valor Total Descapitalização]');
CALL GerarMetricaBiCompleta('vValDescapEmAreaFrontBi',  'vFApreFront',  '[Valor Total Descapitalização]');

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga das variáveis das Métricas de Apreensões;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
