TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_MATERIA_RE do TEMP_DIM_CASOS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
// Carga do BI DE ESTATÍSTICAS CRIMINAIS do NGE/COP/DICOR/PF
// DIM_MATERIA_RE DO DIM_CASOS COM LINK TABLE
// --------------------------------------------------------------------------------------
// Carregamento da tabela DIM_MATERIA_RE a partir do arquivo DIM_CASOS.qvd


DIM_MATERIA_RE:
LOAD
    AutoNumberHash128("Proc. Identificação") AS [%PROC_IDENTIFICACAO_KEY],
	SubField("Proc. Matéria Registro Especial",';',IterNo()) AS "Proc. Matéria Registro Especial"
RESIDENT TEMP_DIM_CASOS
WHILE IterNo()<=SubStringCount("Proc. Matéria Registro Especial",';')+1;

DROP TABLE TEMP_DIM_CASOS;

CALL StoreAndDrop('DIM_MATERIA_RE', '$(vCaminhoTransformadosV3)');

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga DIM_MATERIA_RE do TEMP_DIM_CASOS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
