TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando DIM_APREENSOES do TEMP_DIM_CASOS_APREENSAO_BENS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
DIM_APREENSOES:
LOAD Distinct
    AutoNumberHash128("GestãoBens Item ID") AS [%GESTAO_BENS_ITEM_ID_KEY],
    "GestãoBens Item ID", // Chave primária com duplicidade com 22 caracteres
// ACRESCENTADO PARA COLOCAR AS DATAS NAS DIMENSÕES
	Date("GestãoBens Item Data Apreensão") as "Data da Apreensão",
    year("GestãoBens Item Data Apreensão") as "Ano da Apreensão",
    month("GestãoBens Item Data Apreensão") as "Mês da Apreensão",
    Num(MONTH("GestãoBens Item Data Apreensão")) as "Mês (Num) da Apreensão",
    "GestãoBens Procedimento Situação ID", // Texto com 4 caracteres no máximo (só tem quando SISCART)
    "GestãoBens Procedimento ID", // Texto com 25 caracteres (sem registros faltantes)
    "GestãoBens Apreensão ID", // Texto com 14 caracteres (só tem quando SISCART)
    "GestãoBens Apreensão Unidade Sigla", // Texto com 30 caracteres (sem registros faltantes)
    "GestãoBens Apreensão Unidade Cidade", // Texto com 23 caracteres (só tem quando SISCART)
    "GestãoBens Apreensão Unidade UF", // Texto com 2 caracteres (sem registros faltantes)
    "GestãoBens Procedimento Número", // Texto com 17 caracteres (sem registros faltantes)
    "GestãoBens Procedimento Ano", // Texto com 4 caracteres (sem registros faltantes)
    "GestãoBens Procedimento Cartório", // Texto com 3 caracteres (só tem quando SISCART)
//////////////// comentado pois incluído na LINK_TABLE_APREENSOES_OPERACOES_CASOS ////////////////
//    "Proc. Identificação", // Texto com 32 caracteres (353 registros faltantes)
    "GestãoBens Procedimento Original", // Texto com 32 caracteres (sem registros faltantes)
    "GestãoBens Procedimento Tipo", // Texto com 3 caracteres (sem registros faltantes)
    "GestãoBens Apreensão Número", // Texto com 10 digitos (só tem quando SISCART)
    "GestãoBens Apreensão Usuário Matrícula", // Número Real
    "GestãoBens Apreensão Usuário Nome", // Texto com 49 caracteres
    "GestãoBens Item Número", // Texto com 12 caracteres (sem registros faltantes)
    "GestãoBens Item Lacre", // Texto Longo
    "GestãoBens Item Vínculo", // Texto com 51 caracteres (só tem quando ePol)
    "GestãoBens Item Custódia", // Texto com 72 caracteres
    "GestãoBens Item Unidade Custódia", // Texto com 30 caracteres
    "GestãoBens Item Unidade UF Custódia", // Texto com 2 caracteres
    "GestãoBens Item Custódia Tipo", // Texto com 27 caracteres
//     "GestãoBens Item Material ID", // Número Real (sem registros faltantes)
//     "GestãoBens Item Material", // Texto Longo
    "GestãoBens Item Material Original", // Texto Longo
    "GestãoBens Item Material Observação", // Texto Longo
    "GestãoBens Item Material Observação ePol", // Texto Longo
    "GestãoBens Item Placa Veículo", // Texto com 15 caracteres
    "GestãoBens Item Depósito", // Texto com 72 caracteres
    "GestãoBens Item Unidade e Depósito", // Texto com 92 caracteres
    "GestãoBens Item Material Tipo", // Texto com 80 caracteres (20 registros distintos) igual ao "GestãoBens Item Material Categoria"
//     "GestãoBens Item Material Classe", // Texto com 132 caracteres (143 registros distintos)
    "GestãoBens Item Material Classe Original", // Texto com 132 caracteres (143 registros distintos)
//     "GestãoBens Item Material Categoria", // Texto com 80 caracteres (20 registros distintos)
    "GestãoBens Item Material Categoria Original", // Texto com 80 caracteres (20 registros distintos)
//     "GestãoBens Item Material Subclasse Código", // Texto com 8 caracteres (782 registros distintos)
    "GestãoBens Item Material Subclasse Código Original", // Texto com 8 caracteres (782 registros distintos)
    "GestãoBens Item Arma Espécie CGPRE", // novo campo de texto inserido pela CGPRE com tipo de armas conforme taxonomia utilizada pela CGPRE
	"GestãoBens Item Munições Espécie CGPRE", // novo campo de texto inserido pela CGPRE com tipo de munições conforme taxonomia utilizada pela CGPRE
    "GestãoBens Item Arma Marca", // Texto com 64 caracteres
    "GestãoBens Item Arma Espécie", // Texto com 23 caracteres
    "GestãoBens Item Arma Modelo", // Texto com 50 caracteres
    "GestãoBens Item Arma Calibre", // Texto com 30 caracteres
    "GestãoBens Item Arma Série", // Texto com 30 caracteres
    "GestãoBens Item Arma País", // Texto com 25 caracteres
    "GestãoBens Item Arma Importador", // Texto com 49 caracteres
    "GestãoBens Apreensão Detentor Nome", // Texto com 50 caracteres
    "GestãoBens Apreensão Detentor CPF", // Número Real
    "GestãoBens Item Laudo", // Texto com 50 caracteres
    "GestãoBens Item Localização ID", // Número Real
    "GestãoBens Item Destinação", // Texto Longo com 1000 caracteres
    "GestãoBens Item Observação Depósito", // Texto Longo com 1046 caracteres
    "GestãoBens Item Localização Interna", // Texto com 204 caracteres
    "GestãoBens Item Desmembramento Pai", // Número Real
    // "GestãoBens Procedimento Processo Número", // Texto com 34 caracteres
    // "GestãoBens Procedimento Processo Seção", // Texto com 99 caracteres
    // "GestãoBens Procedimento Processo Tribunal", // Texto com 49 caracteres
    // "GestãoBens Procedimento Processo Órgão", // Texto com 121 caracteres
    // "GestãoBens Procedimento Processo MPF", // Número Real
    "GestãoBens Procedimento Incidência Penal Princ.", // Texto com 254 caracteres
    "GestãoBens Procedimento Situação", // Texto com 28 caracteres
    "GestãoBens Item Último Movimento", // Texto com 30 caracteres
    "Gestãobens Item Decisão", // Texto com 63 caracteres (sem registros faltantes)
    "Gestãobens Número SEI (Alienação SENAD)", // Texto com 17 caracteres
    "GestãoBens Apreensão Sistema", // Texto (Siscart/ePol) (sem registros faltantes)
    "GestãoBens Alerta Unidades Diferentes", // Texto (Sim/Não) (sem registros faltantes)
    "GestãoBens Alerta Apreensão sem Procedimento", // Texto (Sim/Não) (sem registros faltantes)
    "GestãoBens Item Em Custódia", // Texto (Sim/Não) (sem registros faltantes)
    "GestãoBens Item Em Depósito", // Texto (Sim/Não) (sem registros faltantes)
    "GestãoBens Item Passou Depósito", // Texto (Sim/Não) (sem registros faltantes)
    "GestãoBens Procedimento Sistema", // Texto (Siscart/ePol) (sem registros faltantes)
    PLANILHACGPRE
RESIDENT TEMP_DIM_CASOS_APREENSAO_BENS;

DROP TABLE TEMP_DIM_CASOS_APREENSAO_BENS;

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída carga DIM_APREENSOES do TEMP_DIM_CASOS_APREENSAO_BENS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
