TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Corrigindo erro de sinconização do ePol com SIGACrim;
TRACE >>> Carregando TEMP_SIGACrimHomologadas;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;


// Corrige erro de sinconização do ePol com SIGACrim que faz com que as unidades
// da operação não estejam sendo sincronizadas com as mudanças das unidades 
// ocorridas no epol.
// Ocorre que o Painel SIGACrim Operações está refletindo essa falha de 
// sincronização e o COP orientou que o painel reflitisse a lógica do Painel 
// SIGACrim Operações, para que, quando forem chegar os números com o 
// passo-a-passo de conferência das estatísticas, tudo esteja correto.
// Por isso, esta seção imita o comportamento do SIGACrim que sofre hoje com a 
// falta de sincronização das unidades e áreas com o ePol.
TEMP_SIGACrimHomologadas:
LOAD DISTINCT
    // 1) Fonte padronizada de unidade
    If(
        Len(Trim(UNIDADE)) = 0,
        ApplyMap('MapIPLCasoUnidade', IPL),
        UNIDADE
    ) as UnidadeBase,
    // 2) Fonte padronizada de área de atribuição
    If(
        Len(Trim(UNIDADE)) = 0,
        ApplyMap('MapIPLAreaCaso', IPL),
        AREAATRIBUICAO
    ) as AreaBase,
    // 3) Fonte padronizada de diretoria
    If(
        Len(Trim(UNIDADE)) = 0,
        ApplyMap('MapIPLCasoDiretoria', IPL),
        ApplyMap('AREADIRETORIAMapping', AREAATRIBUICAO)
    ) as DiretoriaBase,
    // 4) Fonte padronizada de coordenação-geral
    If(
        Len(Trim(UNIDADE)) = 0,
        ApplyMap('MapIPLCasoCG', IPL),
        ApplyMap('AREACOORDENACAOGERALMapping', AREAATRIBUICAO)
    ) as CoordenacaoBase,
    *
RESIDENT TEMP_TEMP_SIGACrimHomologadas;

DROP TABLE TEMP_TEMP_SIGACrimHomologadas;


TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída correção erro de sinconização do ePol com SIGACrim;
TRACE >>> Carregando TEMP_SIGACrimHomologadas;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
