TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Iniciando das VARIÁVEIS DE AMBIENTE;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

//-----------------------------------------------------------------------------------------------
// Variáveis 
//-----------------------------------------------------------------------------------------------

SET vCaminhoTransformados = 'lib://CORP_DICOR_NGE/BI_NGE_ESTATISTICAS/T_'; // caminho dos arquivos transformados
SET vCaminhoTransformadosV2 = 'lib://CORP_DICOR_NGE/BI_NGE_ESTATISTICAS/T2_'; // caminho dos arquivos transformados versão NOVA com eventos e calendário canônico
SET vCaminhoTransformadosV3 = 'lib://CORP_DICOR_NGE/BI_NGE_ESTATISTICAS/T3_'; // caminho dos arquivos transformados versão NOVA com eventos e sm calendário canônico

SET HidePrefix = '%';

//-----------------------------------------------------------------------------------------------
// Variáveis para títulos do botões que mostram ou definem as métricas 
// mostradas no painel:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

SET vTitBotMostraMetricasPainel = 
PICK(vMostrarValAbsouRelaoEfetouPfEmNum + 1,
        'Valores inteiros',
        'Valores p/ efetivo PJ',
        'Valores PF EM NÚMEROS'
    )
;

SET vTitBotDefineMetricasPainel = 
PICK(vMostrarValAbsouRelaoEfetouPfEmNum + 1,
        'Mostrar valores p/ efetivo PJ',
        'Mostrar valores PF EM NÚMEROS',
        'Mostrar valores inteiros'
    )
;

//-----------------------------------------------------------------------------------------------
// Variável definir valores das variáveis que definem as métricas  mostradas no
// painel:
//      - numeros absolutos
//      - números por efetivo
//      - números PF EM NÚMEROS
//-----------------------------------------------------------------------------------------------

SET vValVarDefineMetricasPainel = 
PICK(vMostrarValAbsouRelaoEfetouPfEmNum + 1,
		1,
        2,
        0
    )
;

//-----------------------------------------------------------------------------------------------
// Variável para definir uma cor especial para os botões 'Painéis', 'Análises' e 'Relatórios' 
// de acordo com o tipo de página ativa:
//      - 'Painéis'
//      - 'Análises'
//      - 'Relatórios'
//-----------------------------------------------------------------------------------------------

SET vCorBotaoPainel = '
if(''@(vPaginaAtiva)''=''Painel'',   
	''#87205d'',
    ''#070053''
)
';

Call TratarExpansaoMacro(vCorBotaoPainel);

SET vCorBotaoAnalise = '
if(''@(vPaginaAtiva)''=''Analise'',   
	''#87205d'',
    ''#070053''
)
';

Call TratarExpansaoMacro(vCorBotaoAnalise);

SET vCorBotaoRelatorio = '
if(''@(vPaginaAtiva)''=''Relatorio'',   
	''#87205d'',
    ''#070053''
)
';

Call TratarExpansaoMacro(vCorBotaoRelatorio);

SET vCorBotaoAjuda = '
if(''@(vPaginaAtiva)''=''Ajuda'',   
	''#87205d'',
    ''#070053''
)
';

Call TratarExpansaoMacro(vCorBotaoAjuda);

SET vCorBotaoPaginaInicial = '
if(''@(vPaginaInicial)''=''Pagina_Inicial'',   
	''#87205d'',
    ''#070053''
)
';

Call TratarExpansaoMacro(vCorBotaoPaginaInicial);


//-----------------------------------------------------------------------------------------------
// Variáveis para definir as cores das medidas e dos segmentos dos gráficos 
// de acordo com o tipo de medida:
//      - Operações
//      - Prisões e Buscas
//      - Apreensões
//      - Inquéritos, Registros Especiais e Termos Circunstanciados
//-----------------------------------------------------------------------------------------------

SET vCorMedidaOperacao = '#070053';
SET vCorMedidaOperacaoSegmento1 = '#554a7b';
SET vCorMedidaOperacaoSegmento2 = '#a79ec1';
SET vCorMedidaOperacaoSegmento3 = '#ded1ff';

SET vCorMedidaPrisaoBusca = '#8a85c6';
SET vCorMedidaPrisaoBuscaSegmento1 = '#726ea4';
SET vCorMedidaPrisaoBuscaSegmento2 = '#b1b5e0';
SET vCorMedidaPrisaoBuscaSegmento3 = '#d9dcff';


SET vCorMedidaApreensao = '#006580';
SET vCorMedidaApreensaoSegmento1 = '#138094';
SET vCorMedidaApreensaoSegmento2 = '#5fbbcb';
SET vCorMedidaApreensaoSegmento3 = '#74f0ff';


SET vCorMedidaInqueritoRegistroTermo = '#003a85';
SET vCorMedidaInqueritoRegistroTermoSegmento1 = '#004298';
SET vCorMedidaInqueritoRegistroTermoSegmento2 = '#7485cf';
SET vCorMedidaInqueritoRegistroTermoSegmento3 = '#b8d2ff';
