TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Gravando QVDs;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
/*
GRAVA OS ARQUIVOS EXTRAÍDOS E TRANSFORMADOS PARA FAZER A MODELAGEM COM LINK TABLE
*/
TRACE >>> Gravando QVD TEMP_TNBIA;
CALL StoreAndDrop('TEMP_TNBIA', '$(vCaminhoExtraidosV2)'); //

TRACE >>> Gravando QVD Area_Diretoria_CG;
CALL StoreAndDrop('Area_Diretoria_CG', '$(vCaminhoExtraidosV2)'); //

TRACE >>> Gravando QVD TEMP_DIM_CASOS_APREENSAO_BENS;
CALL StoreAndDrop('TEMP_DIM_CASOS_APREENSAO_BENS', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_TEMP_SIGACrimHomologadas;
CALL StoreAndDrop('TEMP_TEMP_SIGACrimHomologadas', '$(vCaminhoExtraidosV2)'); // DROP !!!!!!
// CALL StoreAndDrop('TEMP_SIGACrimHomologadas', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_Palas_Operacoes_Tratadas_2022_2023;
CALL StoreAndDrop('TEMP_Palas_Operacoes_Tratadas_2022_2023', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_DIM_CASOS_DATA;
CALL StoreAndDrop('TEMP_DIM_CASOS_DATA', '$(vCaminhoExtraidosV2)'); //
// TRACE >>> Gravando QVD TEMP_TEMP_DIM_CASOS;
// CALL StoreAndDrop('TEMP_TEMP_DIM_CASOS', '$(vCaminhoExtraidosV2)'); // DROP !!!!!!
TRACE >>> Gravando QVD TEMP_DIM_CASOS;
CALL StoreAndDrop('TEMP_DIM_CASOS', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_DIM_CASOS_TIPO_PENAL;
CALL StoreAndDrop('TEMP_DIM_CASOS_TIPO_PENAL', '$(vCaminhoExtraidosV2)'); //
// TRACE >>> Gravando QVD TEMP_TABELAOEVENTOS;
// CALL StoreAndDrop('TEMP_TABELAOEVENTOS', '$(vCaminhoExtraidosV2)'); //
// TRACE >>> Gravando QVD TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO;
// CALL StoreAndDrop('TEMP_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO', '$(vCaminhoExtraidosV2)'); //
// TRACE >>> Gravando QVD TEMP_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRO;
// CALL StoreAndDrop('TEMP_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRO', '$(vCaminhoExtraidosV2)'); //
// TRACE >>> Gravando QVD TEMP_EVENTOS_PRISOES_GCAP;
// CALL StoreAndDrop('TEMP_EVENTOS_PRISOES_GCAP', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_ARMAS_MUNICOES_DROGAS_FINAL_CGPRE;
CALL StoreAndDrop('TEMP_ARMAS_MUNICOES_DROGAS_FINAL_CGPRE', '$(vCaminhoExtraidosV2)'); //


TRACE >>> Gravando QVD TEMP_TABELAOEVENTOS;
CALL StoreAndDrop('TEMP_TABELAOEVENTOS', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_EVENTOS_PRISOES;
CALL StoreAndDrop('TEMP_EVENTOS_PRISOES', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_EVENTOS_APREENSOES;
CALL StoreAndDrop('TEMP_EVENTOS_APREENSOES', '$(vCaminhoExtraidosV2)'); //


TRACE >>> Gravando QVD TEMP_DIM_SERVIDOR_ATIVO;
CALL StoreAndDrop('TEMP_DIM_SERVIDOR_ATIVO', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_DIM_UNIDADE;
CALL StoreAndDrop('TEMP_DIM_UNIDADE', '$(vCaminhoExtraidosV2)'); //
TRACE >>> Gravando QVD TEMP_DIM_HIERARQUIA_TECNICA;
CALL StoreAndDrop('TEMP_DIM_HIERARQUIA_TECNICA', '$(vCaminhoExtraidosV2)'); //