TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_TABELAOEVENTOS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
// Carregando o TabelaoEventos.qvd registrando a ordem original dos registros do QVD
TEMP_TABELAOEVENTOS:
LOAD DISTINCT
	recno() as id_ordem_original_evento, // chave substituta vinda da ordem de carga do QVD original
    id_evento,
    id_etapa_evento_fk,
    cd_tipo_evento_fk,
    IPL,
    id_eventos_pf,
    id_eventos_estrangeiros,
    id_eventos_externos,
    dt_evento,
    dt_validacao,
    dt_homologacao,
    dt_insert,
    dt_update,
    ds_codinome,
    descricao_evento,
    ob_link,
    st_username_ultima_alteracao,
    cd_uf_fk,
    sg_uf,
    cd_municipio_fk,
    no_municipio,
    no_municipio_evento,
    no_pais_evento,
    ds_tipo_procedimento,
    ds_etapa_evento,
    cd_area_atribuicao_epol,
    ds_area_atribuicao,
    cd_unidade_registradora,
    unidade_registradora,
    eh_unidade_executora,
    eh_unidade_executora_participacao,
    eh_unidade_executora_info,
    eh_unidade_executora_apoio,
    tem_relacao_operacao,
    tem_relacao_operacoes,
    cd_onu_pais_estrangeiro,
    cd_iso_apha3_estrangeiro,
    no_pais_estrangeiro,
    ds_orgao_cooperacao_outro_estrangeiro,
    no_orgao_cooperacao_externo,
    no_uf_orgao_externo,
    no_uf_doc_externo,
    no_municipio_doc_externo,
    houve_apreensao_temp,
    houve_prisao_temp,
    qtd_presos,
    houve_apreensao,
    houve_prisao,
    id_unidade,
    cd_tipo_participacao,
    ds_participacao,
    unidade_participante,
    tipos_prisao
// FROM [lib://CORP_DICOR_COP/TabelaoEventos.qvd]
FROM [$(vCarregaTabelaoEventos)]
(qvd)
WHERE MATCH(ds_etapa_evento, 'Homologada') > 0
		AND Year(dt_evento) > 2023
;
LEFT JOIN (TEMP_TABELAOEVENTOS)
LOAD DISTINCT
    $(vTransformaProcIdentificacaoEmCaso)
    AS IPL,
    "Proc. Identificação"
RESIDENT TEMP_TEMP_DIM_CASOS
WHERE "Proc. Tipo" <> 'NC'
;

// NoConcatenate
// [TabelaoEventos_01_04_2026]:
// LOAD *
// FROM [lib://CORP_DICOR_COP/TabelaoEventos.qvd]
// (qvd);
// CALL StoreCsv('TabelaoEventos_01_04_2026', '$(vCaminhoTabelasTeste)'); //
// CALL StoreAndDrop('TabelaoEventos_01_04_2026', '$(vCaminhoTabelasTeste)'); //

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída CArga TEMP_TABELAOEVENTOS;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
