TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Carregando TEMP_EVENTOS_APREENSOES;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TEMP_EVENTOS_APREENSOES:
LOAD distinct
    id_evento,
    cd_item_epol_fk,
    cd_categoria_epol_fk,
    cd_classe_epol_fk,
    id_evento_apreensao,
    nr_apreensao,
    dt_apreensao,
    ds_apreensao,
    nr_caso,
    ds_item,
    qt_item,
    st_selecionado,
    ds_local_apreensao,
    un_item
// FROM [lib://CORP_DICOR_COP/Eventos_Apreensoes.qvd]
FROM [$(vCarregaEventos_Apreensoes)]
(qvd);

// NoConcatenate
// [Eventos_Apreensoes_01_04_2026]:
// LOAD *
// FROM [lib://CORP_DICOR_COP/Eventos_Apreensoes.qvd]
// (qvd);
// CALL StoreCsv('Eventos_Apreensoes_01_04_2026', '$(vCaminhoTabelasTeste)'); //
// CALL StoreAndDrop('Eventos_Apreensoes_01_04_2026', '$(vCaminhoTabelasTeste)'); //

TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Concluída Carga TEMP_EVENTOS_APREENSOES;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
