TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
TRACE >>> Iniciando carga das Tabelas das Dimensões;
TRACE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;

[DIM_OPERACOES]:
LOAD DISTINCT
    [%ID_OPERACAO_KEY]
    ,[ID_OPERACAO]
    ,[Caso_de_Operação]
    ,[Região]
    ,[Data Prevista para Deflagração]
    ,[Ano Previsto para Deflagração]
    ,[Mês Previsto para Deflagração]
    ,[Mês (Num) Previsto para Deflagração]
    ,[Data da Deflagração]
    ,[Ano da Deflagração]
    ,[Mês da Deflagração]
    ,[Mês (Num) da Deflagração]
    ,[Data do Cadastro]
    ,[Ano do Cadastro]
    ,[Mês do Cadastro]
    ,[Mês (Num) do Cadastro]
    ,[Data de Início]
    ,[Ano de Início]
    ,[Mês de Início]
    ,[Mês (Num) de Início]
    ,[Data da Homologação]
    ,[Ano da Homologação]
    ,[Mês da Homologação]
    ,[Mês (Num) da Homologação]
    ,[Data(gPol) Prevista para Deflagração]
    ,[Ano(gPol) Previsto para Deflagração]
    ,[Mês(gPol) Previsto para Deflagração]
    ,[Mês (Num)(gPol) Previsto para Deflagração]
    ,[UF_OPERACAO]
    ,[UNIDADE_OPERACAO]
    ,[NOME_OPERACAO]
    ,[DS_OPERACAO]
    ,[DS_VISIBILIDADE]
    ,[ID_UNIDADE]
    ,[ETAPAOPERACAO]
    ,[UNIDADE_FRONTEIRA]
    ,[TIPO_RIF]
    ,[DS_ATIVIDADE_ECONOMICA]
    ,[TENTACULOS_SEI_IPJ]
    ,[PRE_NR_REGISTROS_ESPECIAIS]
    ,[PRE_DS_GRUPO_TATICO]
    ,[PRE_OB_PRE_DEFLAGRACAO]
    ,[ID_DADOS_GPOL]
    ,[ID_DEFLAGRACAO_GPOL]
    ,[PRE_GPOL_ST_AUX_GRUPO_TATICO]
    ,[UF_DESMATAMENTO]
    ,[DS_NUMERO_CASO_SISTEMA_RAPINA]
    ,[NR_SERIE_P2P]
    ,[JUSTIFICATIVA_CRIME_FAZENDARIO]
    ,[JUSTIFICATIVA_CRIME_FINANCEIRO]
    ,[DESCRICAO_BENEFICIO]
    ,[OB_PREJUIZOS_EVITADOS_UNIAO]
    ,[OB_VANTAGEM_INDEVIDA_SERVIDOR]
    ,[TIPO_ERRADICACAO]
    ,[OB_BANCO_DADOS_INVADIDOS]
    ,[OB_IDENTIFICACAO_MODUS_OPERANDI]
    ,[OB_IDENTIFICACAO_SITES_GRUPOS]
    ,[INFO_POLICIA_JUDICIARIA_ALTA_TECNOLOGIA]
    ,[NUMERO_LAUDO_PERICIA_INFORMATICA]
    ,[Foi relatada após deflagrada]
    ,[Unidade Sigla da Operação]
    ,[Unidade UF da Operação]
    ,[Área de Atribuição da Operação]
    ,[Diretoria da Operação]
    ,[Coordenação-Geral da Operação]
FROM [$(vCaminhoTransformadosV3)DIM_OPERACOES.qvd]
(qvd);

/**********************************************************************************
Carga dos Atributos das Operações com FOR EACH, pois são muitos LOAD, mas todos têm
o formato bem parecido, com a dimensão a ser carregada sendo o nome da tabela menos 
o prefixo DIM_, como no exemplo abaixo:
 [DIM_PAIS_COOPERACAO_POLICIAL]:
 LOAD
    [%ID_OPERACAO_KEY]
     [PAIS_COOPERACAO_POLICIAL]
 FROM [$(vCaminhoTransformadosV3)DIM_PAIS_COOPERACAO_POLICIAL.qvd]
 (qvd);
Assim, para evitar repetir várias vezes a mesma forma, utilizei a 
estrutura de repetição FOR EACH.
***********************************************************************************/

load * inline [
FIELD
DIM_PAIS_COOPERACAO_POLICIAL
DIM_ORGANISMO_INTERNACIONAL
DIM_PAIS_COOPERACAO_JURIDICA
DIM_NO_ORGAO_COOPERACAO
DIM_ID_SIS
DIM_ID_SIMBA
DIM_DS_MEIO_EVASAO_DIVISA
DIM_PAIS_EVASAO_DIVISAS
DIM_PAIS_CRIME_TRANSNACIONAL
DIM_UF_CRIME_INTERESTADUAL
DIM_FACCAO_DESCRICAO
DIM_PAIS_FRONTEIRA
DIM_DS_TERRA_INDIGENA
DIM_UNIDADE_CONSERVACAO
DIM_RE_SEQUESTRO
DIM_TIPO_ESPECIE_AMBIENTAL
DIM_TIPO_ILICITO
DIM_MUNICIPIO_DESMATAMENTO
DIM_NR_SERIE_FT_IDV
DIM_DS_MEIO_CRIME_ALTA_TECNOLOGIA
DIM_DS_IMPACTO_CRIME_ALTA_TECNOLOGIA
DIM_MODAIS_UTILIZADOS
DIM_FORMA_CRIME_ODIO
DIM_PRE_NO_ORGAO_COOPERACAO
DIM_PRE_GPOL_UF_MUNICIPIOS_LISTA
];

FOR EACH vTabela IN FieldValueList('FIELD')
    LET vCampo = Replace('$(vTabela)','DIM_','');
    $(vTabela):
    LOAD DISTINCT
        [%ID_OPERACAO_KEY]
        ,[$(vCampo)]
    FROM [$(vCaminhoTransformadosV3)$(vTabela).qvd]
    (qvd);
NEXT

[DIM_Caso_de_RE_de_Recuperação_de_Ativos]:
LOAD DISTINCT
    [%ID_OPERACAO_KEY]
    ,[Caso_de_RE_de_Recuperação_de_Ativos]
FROM [$(vCaminhoTransformadosV3)DIM_Caso_de_RE_de_Recuperação_de_Ativos.qvd]
(qvd);

[DIM_EFETIVOS_GPOL]:
LOAD
    [%ID_OPERACAO_KEY]
    ,[CARGO]
    ,[QTD]
FROM [$(vCaminhoTransformadosV3)DIM_EFETIVOS_GPOL.qvd]
(qvd);

[DIM_APREENSOES]:
LOAD DISTINCT
    [%GESTAO_BENS_ITEM_ID_KEY]
    ,[GestãoBens Item ID]
    ,[Data da Apreensão]
    ,[Ano da Apreensão]
    ,[Mês da Apreensão]
    ,[Mês (Num) da Apreensão]
    ,[GestãoBens Procedimento Situação ID]
    ,[GestãoBens Procedimento ID]
    ,[GestãoBens Apreensão ID]
    ,[GestãoBens Apreensão Unidade Sigla]
    ,[GestãoBens Apreensão Unidade Cidade]
    ,[GestãoBens Apreensão Unidade UF]
    ,[GestãoBens Procedimento Número]
    ,[GestãoBens Procedimento Ano]
    ,[GestãoBens Procedimento Cartório]
    ,[GestãoBens Procedimento Original]
    ,[GestãoBens Procedimento Tipo]
    ,[GestãoBens Apreensão Número]
    ,[GestãoBens Apreensão Usuário Matrícula]
    ,[GestãoBens Apreensão Usuário Nome]
    ,[GestãoBens Item Número]
    ,[GestãoBens Item Lacre]
    ,[GestãoBens Item Vínculo]
    ,[GestãoBens Item Custódia]
    ,[GestãoBens Item Unidade Custódia]
    ,[GestãoBens Item Unidade UF Custódia]
    ,[GestãoBens Item Custódia Tipo]
//     ,[GestãoBens Item Material ID]
//     ,[GestãoBens Item Material]
    ,[GestãoBens Item Material Original]
    ,[GestãoBens Item Material Observação]
    ,[GestãoBens Item Material Observação ePol]
    ,[GestãoBens Item Placa Veículo]
    ,[GestãoBens Item Depósito]
    ,[GestãoBens Item Unidade e Depósito]
    ,[GestãoBens Item Material Tipo]
//     ,[GestãoBens Item Material Classe]
    ,[GestãoBens Item Material Classe Original]
//     ,[GestãoBens Item Material Categoria]
    ,[GestãoBens Item Material Categoria Original]
//     ,[GestãoBens Item Material Subclasse Código]
    ,[GestãoBens Item Material Subclasse Código Original]
    ,[GestãoBens Item Arma Espécie CGPRE]
	,[GestãoBens Item Munições Espécie CGPRE]
    ,[GestãoBens Item Arma Marca]
    ,[GestãoBens Item Arma Espécie]
    ,[GestãoBens Item Arma Modelo]
    ,[GestãoBens Item Arma Calibre]
    ,[GestãoBens Item Arma Série]
    ,[GestãoBens Item Arma País]
    ,[GestãoBens Item Arma Importador]
    ,[GestãoBens Apreensão Detentor Nome]
    ,[GestãoBens Apreensão Detentor CPF]
    ,[GestãoBens Item Laudo]
    ,[GestãoBens Item Localização ID]
    ,[GestãoBens Item Destinação]
    ,[GestãoBens Item Observação Depósito]
    ,[GestãoBens Item Localização Interna]
    ,[GestãoBens Item Desmembramento Pai]
    ,[GestãoBens Procedimento Incidência Penal Princ.]
    ,[GestãoBens Procedimento Situação]
    ,[GestãoBens Item Último Movimento]
    ,[Gestãobens Item Decisão]
    ,[Gestãobens Número SEI (Alienação SENAD)]
    ,[GestãoBens Apreensão Sistema]
    ,[GestãoBens Alerta Unidades Diferentes]
    ,[GestãoBens Alerta Apreensão sem Procedimento]
    ,[GestãoBens Item Em Custódia]
    ,[GestãoBens Item Em Depósito]
    ,[GestãoBens Item Passou Depósito]
    ,[GestãoBens Procedimento Sistema]
FROM [$(vCaminhoTransformadosV3)DIM_APREENSOES.qvd]
(qvd);

[DIM_CASOS]:
LOAD DISTINCT
    [%PROC_IDENTIFICACAO_KEY]
    ,[Proc. Identificação]
    ,[Caso]
    ,[Data da Instauração]
    ,[Data do Relatório]
    ,[Data do Fato]
    ,[Data do Encerramento]
    ,[Ano da Instauração]
    ,[Mês da Instauração]
    ,[Mês (Num) da Instauração]
    ,[Dia da Instauração]
    ,[Ano do Relatório]
    ,[Mês do Relatório]
    ,[Mês (Num) do Relatório]
    ,[Dia do Relatório]
    ,[Ano do Encerramento]
    ,[Mês do Encerramento]
    ,[Mês (Num) do Encerramento]
    ,[Dia do Encerramento]
    ,[Ano do Fato]
    ,[Mês do Fato]
    ,[Mês (Num) do Fato]
    ,[Dia do Fato]
    ,[Proc. Data Última Movimentação]
    ,[Proc. Data Último Despacho]
    ,[Proc. Data Tarefa Pendente]
    ,[Procedimento ID]
    ,[Proc. Crime CEP]
    ,[Proc. Órgão Vítima Original]
    ,[Proc. Escrivão Matrícula]
    ,[Proc. Delegado Matrícula]
    ,[Proc. Processo #]
    ,[Proc. Processo Seção]
    ,[Proc. Processo Tribunal]
    ,[Proc. Processo Vara]
    ,[Proc. Processo MPF]
    ,[Proc. Situação Sigla]
    ,[Proc. Delegacia]
    ,[Proc. Delegacia Instauração]
    ,[Proc. Incidência Penal Principal]
    ,[Lotação Sigla]
    ,[Proc. Origem Documento]
    ,[Município Crime UF]
    ,[País Crime]
    ,[Proc. Tipo Local]
    ,[Município Crime Código]
    ,[Município Crime]
    ,[Proc. Crime Coord. Geográfica]
    ,[Proc. Tipo Histórico]
    ,[Proc. Delegado Atual]
    ,[Proc. Delegado Situação]
    ,[Proc. Delegado Lotação]
    ,[Proc. Delegado Delegacia]
    ,[Proc. Escrivão]
    ,[Proc. Escrivão Situação]
    ,[Proc. Escrivão Lotação]
    ,[Proc. Escrivão Delegacia]
    ,[Proc. Delegado Instaurador]
    ,[Proc. Delegado Instaurador Cargo]
    ,[Proc. Delegado Instaurador Matrícula]
    ,[Proc. Delegado Relator]
    ,[Proc. Delegado Relator Matrícula]
    ,[Proc. Tipo Encerrado]
    ,[Proc. Tipo Encerrado2]
    ,[Proc. Tipo Encerrado3]
    ,[Proc. Unidade Exercício]
    ,[Proc. Tratamento Especial]
    ,[Proc. Crime Bairro]
    ,[Proc. Delegado Missão Unidade]
    ,[Proc. Escrivão Missão Unidade]
    ,[Proc. Crime CEP Coord.]
    ,[Proc. Outra Matéria Registro Especial]
    ,[Proc. Link]
    ,[Proc. Órgão Vítima]
    ,[Proc. Unidade UF]
    ,[Proc. Unidade Registro]
    ,[Proc. Procedimento Flagrante ID]
    ,[Proc. Procedimento Flagrante Sistema Origem]
    ,[Proc. Procedimento Erro Iniciativa]
    ,[Proc. ePol ID]
    ,[Proc. Siscart ID]
    ,[Proc. DPF Situação]
    ,[Proc. EPF Situação]
    ,[Proc. Área de Atribuição]
    ,[Proc. Diretoria]
    ,[Proc. Coordenação-Geral]
    ,[Unidade de Fronteira do Caso]
FROM [$(vCaminhoTransformadosV3)DIM_CASOS.qvd]
(qvd);

[DIM_CASOS_TIPO_PENAL]:
LOAD DISTINCT
    [%PROC_IDENTIFICACAO_KEY]
    ,[Proc. Lei]
    ,[Proc. Tipo Penal]
    ,[Proc. Lei Artigo]
    ,[Proc. Lei Artigo Isolado]
FROM [$(vCaminhoTransformadosV3)DIM_CASOS_TIPO_PENAL.qvd]
(qvd);

[DIM_MATERIA_RE]:
LOAD DISTINCT
    [%PROC_IDENTIFICACAO_KEY]
    ,[Proc. Matéria Registro Especial]
FROM [$(vCaminhoTransformadosV3)DIM_MATERIA_RE.qvd]
(qvd);

[DIM_CASOS_DATA]:
LOAD DISTINCT
    [%PROC_DATA_ID_KEY]
    ,[Proc_Data ID]
    ,[Proc_Data Data Hora]
    ,[Proc_Data Data]
    ,[Proc_Data Data Ano]
    ,[Proc_Data Data Mês]
    ,[Proc_Data Data Mês (Num)]
    ,[Proc_Data Data Dia]
    ,[Proc_Data Data Ano-Mês]
FROM [$(vCaminhoTransformadosV3)DIM_CASOS_DATA.qvd]
(qvd);

[DIM_SERVIDOR_ATIVO]:
LOAD DISTINCT
    [%UNIDADE_KEY]
    ,[Servidor Unidade Exercício]
    ,[Servidor ID]
    ,[Servidor Matrícula PF]
    ,[Servidor Cargo]
    ,[Servidor Cargo Sigla]
    ,[Servidor Cargo Pertence PF]
    ,[Servidor Nome]
    ,[Servidor Data Nascimento]
    ,[Servidor Sexo]
    ,[Servidor Email Pessoal]
    ,[Servidor Unidade Lotação]
    ,[Servidor Escolaridade]
    ,[Servidor Situação Vínculo]
    ,[Servidor Categoria]
    ,[Servidor Formação Acadêmica]
    ,[Servidor Tipo Cargo]
    ,[Servidor Idade]
    ,[Servidor Data Admissão Cargo]
    ,[Servidor Data Ingresso Serviço Público]
FROM [$(vCaminhoTransformadosV3)DIM_SERVIDOR_ATIVO.qvd]
(qvd);

[DIM_UNIDADE]:
LOAD DISTINCT
    [%UNIDADE_KEY]
    ,[Unidade Sigla1]
    ,[Unidade Sigla2]
    ,[Unidade Sigla3]
    ,[Unidade Sigla4]
    ,[Unidade Sigla5]
    ,[Unidade Sigla6]
    ,[Unidade Sigla Superior]
    ,[Caminho Unidade Sigla]
    ,[Unidade ID]
    ,[Unidade Responsável ID]
    ,[Unidade Sigla]
    ,[Descrição Unidade Sigla]
    ,[Unidade UF]
    ,[Unidade Região]
    ,[Unidade Email]
    ,[Unidade Organizacional]
    ,[Unidade Tipo]
    ,[Unidade SIORG]
    ,[Unidade Conduz IPL]
    ,[Unidade Adicional Fronteira]
    ,[Unidade Circunscrição]
    ,[Unidade Dotação]
    ,[Unidade Município Nome]
    ,[Unidade Município IBGE]
    ,[Unidade Estado UF]
    ,[Unidade Estado Nome]
    ,[Unidade PF Área]
    ,[Unidade Circunscrição Município Sede]
    ,[Unidade Circunscrição UF Sede]
    ,[Unidade Lotação Sigla]
    ,[Unidade Endereço]
    ,[Unidade Endereço CEP]
    ,[Unidade Endereço UF]
    ,[Nível]
FROM [$(vCaminhoTransformadosV3)DIM_UNIDADE.qvd]
(qvd);

[DIM_HIERARQUIA_TECNICA]:
LOAD DISTINCT
    [%UNIDADE_KEY]
    ,[É Unidade Central]
    ,[É Unidade Regional]
    ,[É Base]
    ,[É Unidade Descentralizada]
    ,[É Delegacia Especializada PJ]
    ,[Unidade Sigla Raiz]
    ,[Unidade Sigla Unificada]
    ,[Unidade Central]
    ,[Unidade Central Investigativa]
    ,[Unidade Central Não Investigativa]
    ,[Unidade Regional]
    ,[Unidade Regional Investigativa]
    ,[Unidade Regional Não Investigativa]
    ,[Base]
    ,[Unidade Descentralizada]
    ,[Unidade Descentralizada Investigativa]
    ,[Unidade Descentralizada Não Investigativa]
    ,[Delegacia Especializada PJ]
    ,[Hierarquia Administrativa]
    ,[Hierarquia Técnica]
    ,[PJ/NPJ]
    ,[Unidade Abrangência]
    ,[Unidade PJ/NPJ]
    ,[É DELECOR]
    ,[É DELEFAZ]
    ,[É DELEPAT]
    ,[É DELEPREV]
    ,[É DRE]
    ,[É DELINST]
    ,[É FICCO]
    ,[É GISE]
FROM [$(vCaminhoTransformadosV3)DIM_HIERARQUIA_TECNICA.qvd]
(qvd);

[DIM_UNIDADE_SUBUNIDADE]:
LOAD DISTINCT
    [%UNIDADE_KEY]
    ,[Pertence a Unidade ID]
    ,[Pertence a Unidade Sigla]
FROM [$(vCaminhoTransformadosV3)DIM_UNIDADE_SUBUNIDADE.qvd]
(qvd);

[DIM_OPERACOES_SEM_AREA]:
LOAD DISTINCT
    [ID_OPERACAO_SEM_AREA]
FROM [$(vCaminhoTransformadosV3)DIM_OPERACOES_SEM_AREA.qvd]
(qvd);

[DIM_EVENTOS_OPERACIONAIS]:
LOAD DISTINCT
    [%ID_EVENTOS_KEY]
    ,[id_ordem_original_evento]
    ,[id_evento]
    ,[cd_tipo_evento_fk]
    ,[IPL]
    ,[Data do Evento Operacional]
    ,[Ano do Evento Operacional]
    ,[Mês do Evento Operacional]
    ,[Mês (Num) do Evento Operacional]
    ,[ds_codinome]
    ,[ds_tipo_procedimento]
    ,[ds_etapa_evento]
    ,[cd_tipo_participacao]
    ,[descricao_evento]
    ,[ds_participacao]
FROM [$(vCaminhoTransformadosV3)DIM_EVENTOS_OPERACIONAIS.qvd]
(qvd);

[DIM_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO]:
LOAD
    [%ID_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRAS_KEY]
    ,[id_evento_apreensao]
    ,[cd_item_epol_fk]
    ,[cd_categoria_epol_fk]
    ,[cd_classe_epol_fk]
    ,[nr_apreensao]
    ,[Data do Evento Apreensão Externo/Estrangeiro]
    ,[Ano do Evento Apreensão Externo/Estrangeiro]
    ,[Mês do Evento Apreensão Externo/Estrangeiro]
    ,[Mês (Num) do Evento Apreensão Externo/Estrangeiro]
    ,[ds_apreensao]
    ,[nr_caso]
    ,[ds_item]
    ,[ds_local_apreensao]
    ,[un_item]
FROM [$(vCaminhoTransformadosV3)DIM_EVENTOS_APREENSOES_EXTERNAS_ESTRANGEIRO.qvd]
(qvd);

[DIM_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRO]:
LOAD
    [%ID_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRAS_KEY]
	,[id_evento_prisao]
	,[Nome do Preso em Evento Externo/Estrangeiro]
	,[CPF do Preso em Evento Externo/Estrangeiro]
    ,[ds_documento]
    ,[ds_local_prisao]
FROM [$(vCaminhoTransformadosV3)DIM_EVENTOS_PRISOES_EXTERNAS_ESTRANGEIRO.qvd]
(qvd);

[DIM_TNBIA]:
LOAD DISTINCT
	[%ITEM_SUBCLASSE_KEY]
	,[GestãoBens Item Material Subclasse Código]
    ,[GestãoBens Item Material ID]
    ,[GestãoBens Item Material]
    ,[GestãoBens Item Material Classe]
    ,[GestãoBens Item Material Categoria]
FROM [$(vCaminhoTransformadosV3)DIM_TNBIA.qvd]
(qvd);
